# Generated by Django 5.2.5 on 2025-10-14 16:43

import concurrency.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employmentdocument',
            options={'ordering': ('-created_at',), 'verbose_name': 'Employee Document', 'verbose_name_plural': 'Document Center'},
        ),
        migrations.AlterModelOptions(
            name='historicalemploymentdocument',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Employee Document', 'verbose_name_plural': 'historical Document Center'},
        ),
        migrations.AddField(
            model_name='employmentdocument',
            name='version',
            field=concurrency.fields.VersionField(default=0, help_text='record revision number'),
        ),
        migrations.AddField(
            model_name='historicalemploymentdocument',
            name='version',
            field=concurrency.fields.VersionField(default=0, help_text='record revision number'),
        ),
        migrations.AddField(
            model_name='historicaltimeentry',
            name='version',
            field=concurrency.fields.VersionField(default=0, help_text='record revision number'),
        ),
        migrations.AddField(
            model_name='historicaltimesheet',
            name='version',
            field=concurrency.fields.VersionField(default=0, help_text='record revision number'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='version',
            field=concurrency.fields.VersionField(default=0, help_text='record revision number'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='version',
            field=concurrency.fields.VersionField(default=0, help_text='record revision number'),
        ),
        migrations.AlterField(
            model_name='employmentdocument',
            name='kind',
            field=models.CharField(choices=[('ZV', 'Supplemental Agreement'), ('DV', 'Contract of Employment'), ('AA', 'Leave Request'), ('KM', 'Sick Note'), ('ZZ', 'Other / Miscellaneous')], max_length=2, verbose_name='Kind'),
        ),
        migrations.AlterField(
            model_name='historicalemploymentdocument',
            name='kind',
            field=models.CharField(choices=[('ZV', 'Supplemental Agreement'), ('DV', 'Contract of Employment'), ('AA', 'Leave Request'), ('KM', 'Sick Note'), ('ZZ', 'Other / Miscellaneous')], max_length=2, verbose_name='Kind'),
        ),
    ]
