# Generated by Django 5.2.5 on 2025-11-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltimesheet',
            name='export_payload',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='export_payload',
        ),
        migrations.AlterField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Record note'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Record note'),
        ),
    ]
