# Generated by Django 5.2.5 on 2025-10-14 17:37

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employmentdocument_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentdocument',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AlterField(
            model_name='historicalemploymentdocument',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AlterField(
            model_name='historicaltimeentry',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AlterField(
            model_name='historicaltimesheet',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
    ]
