# Generated by Django 5.2.5 on 2025-11-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_historicaltimesheet_export_payload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleaveyear',
            name='label_year',
            field=models.PositiveIntegerField(verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeleaveyear',
            name='label_year',
            field=models.PositiveIntegerField(verbose_name='Year'),
        ),
    ]
