# Generated by Django 5.2.5 on 2025-10-14 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employmentdocument_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='annual_leave_days_base',
            field=models.PositiveSmallIntegerField(default=25, help_text='Base days per PTO year (for a 5-day-week; legal standard: 25)', verbose_name='Annual leave days (base)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='annual_leave_days_extra',
            field=models.PositiveSmallIntegerField(default=0, help_text='Additional annual days (e.g. disability, agreements).', verbose_name='Extra leave days'),
        ),
        migrations.AddField(
            model_name='employee',
            name='leave_reset_override',
            field=models.DateField(blank=True, help_text='If empty, PTO year resets on Jan 1. If set, PTO year starts each year on this month/day.', null=True, verbose_name='PTO reset date override'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='annual_leave_days_base',
            field=models.PositiveSmallIntegerField(default=25, help_text='Base days per PTO year (for a 5-day-week; legal standard: 25)', verbose_name='Annual leave days (base)'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='annual_leave_days_extra',
            field=models.PositiveSmallIntegerField(default=0, help_text='Additional annual days (e.g. disability, agreements).', verbose_name='Extra leave days'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='leave_reset_override',
            field=models.DateField(blank=True, help_text='If empty, PTO year resets on Jan 1. If set, PTO year starts each year on this month/day.', null=True, verbose_name='PTO reset date override'),
        ),
        migrations.CreateModel(
            name='EmployeeLeaveYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_year', models.PositiveIntegerField(verbose_name='PTO year label')),
                ('period_start', models.DateField(verbose_name='Period start')),
                ('period_end', models.DateField(verbose_name='Period end (exclusive)')),
                ('entitlement_minutes', models.IntegerField(verbose_name='Entitlement (minutes)')),
                ('carry_in_minutes', models.IntegerField(default=0, verbose_name='Carry-in (minutes)')),
                ('manual_adjust_minutes', models.IntegerField(default=0, verbose_name='Manual adjust (minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_years', to='employees.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee PTO year',
                'verbose_name_plural': 'Employee PTO years',
                'ordering': ('-label_year', 'employee_id'),
                'unique_together': {('employee', 'label_year')},
            },
        ),
    ]
