# Generated by Django 5.2.5 on 2025-10-14 20:54

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_annual_leave_days_base_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEmployeeLeaveYear',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('label_year', models.PositiveIntegerField(verbose_name='PTO year label')),
                ('period_start', models.DateField(verbose_name='Period start')),
                ('period_end', models.DateField(verbose_name='Period end (exclusive)')),
                ('entitlement_minutes', models.IntegerField(verbose_name='Entitlement (minutes)')),
                ('carry_in_minutes', models.IntegerField(default=0, verbose_name='Carry-in (minutes)')),
                ('manual_adjust_minutes', models.IntegerField(default=0, verbose_name='Manual adjust (minutes)')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employee', verbose_name='Employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Employee PTO year',
                'verbose_name_plural': 'historical Employee PTO years',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
