# Generated by Django 5.2.5 on 2025-10-19 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_historicalemployeeleaveyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltimesheet',
            name='approved_at_chair',
        ),
        migrations.RemoveField(
            model_name='historicaltimesheet',
            name='approved_at_wiref',
        ),
        migrations.RemoveField(
            model_name='historicaltimesheet',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='approved_at_chair',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='approved_at_wiref',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='submitted_at',
        ),
    ]
