# Generated by Django 5.2.5 on 2025-10-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_remove_historicaltimesheet_approved_at_chair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentdocument',
            name='relevant_third_party',
            field=models.CharField(blank=True, help_text='Name or identifier of relevant third party (e.g. health insurance, accounting firm, ...). Used for PDF receipts. Optional.', max_length=160, verbose_name='Relevant third party'),
        ),
        migrations.AddField(
            model_name='historicalemploymentdocument',
            name='relevant_third_party',
            field=models.CharField(blank=True, help_text='Name or identifier of relevant third party (e.g. health insurance, accounting firm, ...). Used for PDF receipts. Optional.', max_length=160, verbose_name='Relevant third party'),
        ),
        migrations.AlterField(
            model_name='employmentdocument',
            name='details',
            field=models.TextField(blank=True, help_text='Detailed description or verbatim of the document.', verbose_name='Details / body'),
        ),
        migrations.AlterField(
            model_name='employmentdocument',
            name='end_date',
            field=models.DateField(blank=True, help_text='Start date (e.g. of the sick note, the leave request). Leave blank if none or without set end.', null=True, verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='employmentdocument',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set if the document is still active.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='employmentdocument',
            name='kind',
            field=models.CharField(choices=[('ZV', 'Supplemental Agreement'), ('DV', 'Contract of Employment'), ('AA', 'Leave Request'), ('KM', 'Sick Note'), ('ZZ', 'Other / Miscellaneous')], help_text='Type of document.', max_length=2, verbose_name='Kind'),
        ),
        migrations.AlterField(
            model_name='employmentdocument',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Optional PDF file (e.g. the contract or agreement).', null=True, upload_to='employee/docs/%Y/%m/', verbose_name='PDF file'),
        ),
        migrations.AlterField(
            model_name='employmentdocument',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date (e.g. of the sick note, the leave request). Leave blank if none.', null=True, verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='employmentdocument',
            name='title',
            field=models.CharField(blank=True, help_text='Title of document (e.g. leave request from ... to).', max_length=160, verbose_name='Title/Subject'),
        ),
        migrations.AlterField(
            model_name='historicalemploymentdocument',
            name='details',
            field=models.TextField(blank=True, help_text='Detailed description or verbatim of the document.', verbose_name='Details / body'),
        ),
        migrations.AlterField(
            model_name='historicalemploymentdocument',
            name='end_date',
            field=models.DateField(blank=True, help_text='Start date (e.g. of the sick note, the leave request). Leave blank if none or without set end.', null=True, verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='historicalemploymentdocument',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set if the document is still active.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='historicalemploymentdocument',
            name='kind',
            field=models.CharField(choices=[('ZV', 'Supplemental Agreement'), ('DV', 'Contract of Employment'), ('AA', 'Leave Request'), ('KM', 'Sick Note'), ('ZZ', 'Other / Miscellaneous')], help_text='Type of document.', max_length=2, verbose_name='Kind'),
        ),
        migrations.AlterField(
            model_name='historicalemploymentdocument',
            name='pdf_file',
            field=models.TextField(blank=True, help_text='Optional PDF file (e.g. the contract or agreement).', max_length=100, null=True, verbose_name='PDF file'),
        ),
        migrations.AlterField(
            model_name='historicalemploymentdocument',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date (e.g. of the sick note, the leave request). Leave blank if none.', null=True, verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='historicalemploymentdocument',
            name='title',
            field=models.CharField(blank=True, help_text='Title of document (e.g. leave request from ... to).', max_length=160, verbose_name='Title/Subject'),
        ),
    ]
