# Generated by Django 5.2.5 on 2025-10-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employmentdocument_relevant_third_party_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of birth', null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='employee',
            name='insurance_no',
            field=models.CharField(blank=True, help_text='Austrian or international social insurance no.', max_length=40, null=True, verbose_name='Social Insurance number'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of birth', null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='insurance_no',
            field=models.CharField(blank=True, help_text='Austrian or international social insurance no.', max_length=40, null=True, verbose_name='Social Insurance number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='end_override',
            field=models.DateField(blank=True, help_text='End of employment. Override in case of misalignment with assigned Role.', null=True, verbose_name='Employment end (override)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_override',
            field=models.DateField(blank=True, help_text='Start of employment. Override in case of misalignment with assigned Role.', null=True, verbose_name='Employment start (override)'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='end_override',
            field=models.DateField(blank=True, help_text='End of employment. Override in case of misalignment with assigned Role.', null=True, verbose_name='Employment end (override)'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='start_override',
            field=models.DateField(blank=True, help_text='Start of employment. Override in case of misalignment with assigned Role.', null=True, verbose_name='Employment start (override)'),
        ),
    ]
