# Generated by Django 5.2.5 on 2025-09-25 22:57

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0013_historicalrole_default_monthly_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrgInfo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('org_name_long_de', models.CharField(blank=True, max_length=200, verbose_name='Org name (DE, long)')),
                ('org_name_short_de', models.CharField(blank=True, max_length=80, verbose_name='Org name (DE, short)')),
                ('org_name_long_en', models.CharField(blank=True, max_length=200, verbose_name='Org name (EN, long)')),
                ('org_name_short_en', models.CharField(blank=True, max_length=80, verbose_name='Org name (EN, short)')),
                ('uni_name_long_de', models.CharField(blank=True, max_length=200, verbose_name='University (DE, long)')),
                ('uni_name_short_de', models.CharField(blank=True, max_length=120, verbose_name='University (DE, short)')),
                ('uni_name_long_en', models.CharField(blank=True, max_length=200, verbose_name='University (EN, long)')),
                ('uni_name_short_en', models.CharField(blank=True, max_length=120, verbose_name='University (EN, short)')),
                ('org_address', models.TextField(blank=True, help_text='Multiline; used in PDFs/letters.', verbose_name='Organisation address')),
                ('bank_address', models.TextField(blank=True, verbose_name='Bank address')),
                ('bank_name', models.CharField(blank=True, max_length=120, verbose_name='Bank name')),
                ('bank_iban', models.CharField(blank=True, max_length=34, validators=[django.core.validators.RegexValidator('^[A-Z]{2}\\d{2}[A-Z0-9]{10,30}$', 'Enter a valid IBAN (e.g. AT.., DE..).')], verbose_name='Bank IBAN')),
                ('bank_bic', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$', 'Enter a valid BIC (8 or 11 chars).')], verbose_name='Bank BIC')),
                ('org_tax_id', models.CharField(blank=True, max_length=40, verbose_name='VAT/Tax ID')),
                ('default_reference_label', models.CharField(blank=True, help_text='Used as a default in forms/CSV (e.g. "Funktionsgebühr").', max_length=80, verbose_name='Default reference label')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org_chair', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.personrole', verbose_name='Chair')),
                ('org_dty_chair1', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.personrole', verbose_name='1st Deputy Chair')),
                ('org_dty_chair2', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.personrole', verbose_name='2nd Deputy Chair')),
                ('org_dty_chair3', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.personrole', verbose_name='3rd Deputy Chair')),
                ('org_dty_wiref', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.personrole', verbose_name='Deputy Financial Officer')),
                ('org_wiref', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.personrole', verbose_name='Financial Officer (WiRef)')),
            ],
            options={
                'verbose_name': 'historical Organisation info',
                'verbose_name_plural': 'historical Organisation info',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OrgInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name_long_de', models.CharField(blank=True, max_length=200, verbose_name='Org name (DE, long)')),
                ('org_name_short_de', models.CharField(blank=True, max_length=80, verbose_name='Org name (DE, short)')),
                ('org_name_long_en', models.CharField(blank=True, max_length=200, verbose_name='Org name (EN, long)')),
                ('org_name_short_en', models.CharField(blank=True, max_length=80, verbose_name='Org name (EN, short)')),
                ('uni_name_long_de', models.CharField(blank=True, max_length=200, verbose_name='University (DE, long)')),
                ('uni_name_short_de', models.CharField(blank=True, max_length=120, verbose_name='University (DE, short)')),
                ('uni_name_long_en', models.CharField(blank=True, max_length=200, verbose_name='University (EN, long)')),
                ('uni_name_short_en', models.CharField(blank=True, max_length=120, verbose_name='University (EN, short)')),
                ('org_address', models.TextField(blank=True, help_text='Multiline; used in PDFs/letters.', verbose_name='Organisation address')),
                ('bank_address', models.TextField(blank=True, verbose_name='Bank address')),
                ('bank_name', models.CharField(blank=True, max_length=120, verbose_name='Bank name')),
                ('bank_iban', models.CharField(blank=True, max_length=34, validators=[django.core.validators.RegexValidator('^[A-Z]{2}\\d{2}[A-Z0-9]{10,30}$', 'Enter a valid IBAN (e.g. AT.., DE..).')], verbose_name='Bank IBAN')),
                ('bank_bic', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$', 'Enter a valid BIC (8 or 11 chars).')], verbose_name='Bank BIC')),
                ('org_tax_id', models.CharField(blank=True, max_length=40, verbose_name='VAT/Tax ID')),
                ('default_reference_label', models.CharField(blank=True, help_text='Used as a default in forms/CSV (e.g. "Funktionsgebühr").', max_length=80, verbose_name='Default reference label')),
                ('org_chair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='people.personrole', verbose_name='Chair')),
                ('org_dty_chair1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='people.personrole', verbose_name='1st Deputy Chair')),
                ('org_dty_chair2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='people.personrole', verbose_name='2nd Deputy Chair')),
                ('org_dty_chair3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='people.personrole', verbose_name='3rd Deputy Chair')),
                ('org_dty_wiref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='people.personrole', verbose_name='Deputy Financial Officer')),
                ('org_wiref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='people.personrole', verbose_name='Financial Officer (WiRef)')),
            ],
            options={
                'verbose_name': 'Organisation info',
                'verbose_name_plural': 'Organisation info',
            },
        ),
    ]
