# Generated by Django 5.2.5 on 2025-09-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalorginfo',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Master data', 'verbose_name_plural': 'historical Master data'},
        ),
        migrations.AlterModelOptions(
            name='orginfo',
            options={'verbose_name': 'Master data', 'verbose_name_plural': 'Master data'},
        ),
        migrations.AddField(
            model_name='historicalorginfo',
            name='org_public_filing_url',
            field=models.CharField(blank=True, help_text='Do not change without permission.', max_length=128, verbose_name='Public filing URL'),
        ),
        migrations.AddField(
            model_name='orginfo',
            name='org_public_filing_url',
            field=models.CharField(blank=True, help_text='Do not change without permission.', max_length=128, verbose_name='Public filing URL'),
        ),
        migrations.AlterField(
            model_name='historicalorginfo',
            name='default_reference_label',
            field=models.CharField(blank=True, help_text='Used as a default in forms/CSV (e.g. "Rechnung").', max_length=80, verbose_name='Default reference label'),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='default_reference_label',
            field=models.CharField(blank=True, help_text='Used as a default in forms/CSV (e.g. "Rechnung").', max_length=80, verbose_name='Default reference label'),
        ),
    ]
