# Generated by Django 5.2.5 on 2025-11-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorginfo",
            name="payment_plan_disclaimer",
            field=models.TextField(
                blank=True,
                help_text="Disclaimer text shown when person completes payment plan banking details",
                verbose_name="Payment Plan Disclaimer",
            ),
        ),
        migrations.AddField(
            model_name="orginfo",
            name="payment_plan_disclaimer",
            field=models.TextField(
                blank=True,
                help_text="Disclaimer text shown when person completes payment plan banking details",
                verbose_name="Payment Plan Disclaimer",
            ),
        ),
    ]
