# Generated by Django 5.2.5 on 2025-11-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0002_alter_historicalorginfo_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorginfo",
            name="ects_affidavit_1",
            field=models.TextField(
                blank=True,
                help_text="Affidavit text shown when student submits course list",
                verbose_name="ECTS Affidavit 1 (Initial Submission)",
            ),
        ),
        migrations.AddField(
            model_name="historicalorginfo",
            name="ects_affidavit_2",
            field=models.TextField(
                blank=True,
                help_text="Affidavit text shown when student uploads signed form",
                verbose_name="ECTS Affidavit 2 (Form Upload)",
            ),
        ),
        migrations.AddField(
            model_name="orginfo",
            name="ects_affidavit_1",
            field=models.TextField(
                blank=True,
                help_text="Affidavit text shown when student submits course list",
                verbose_name="ECTS Affidavit 1 (Initial Submission)",
            ),
        ),
        migrations.AddField(
            model_name="orginfo",
            name="ects_affidavit_2",
            field=models.TextField(
                blank=True,
                help_text="Affidavit text shown when student uploads signed form",
                verbose_name="ECTS Affidavit 2 (Form Upload)",
            ),
        ),
    ]
