# File: academia_audit/models.py
# Version: 1.0.5
# Author: vas
# Modified: 2025-12-08

from __future__ import annotations
from django.db import models
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from simple_history.models import HistoricalRecords
from concurrency.fields import AutoIncVersionField
from hankosign.utils import state_snapshot
from people.models import PersonRole, Person
from django.core.validators import FileExtensionValidator


def validate_pdf_size(file):
    """Validate PDF size (max 25MB for audit documents)."""
    max_size = 25 * 1024 * 1024  # 25MB
    if file.size > max_size:
        raise ValidationError(
            _("File size must not exceed 25MB. Current: %(size).1f MB") %
            {'size': file.size / (1024 * 1024)}
        )

class AuditSemester(models.Model):
    """
    Audit workflow for a semester's ECTS reimbursements.

    This model manages the audit calculation and approval process
    separate from the inbox filing workflow. References the inbox
    semester and tracks the audit lifecycle.
    """

    # Reference to inbox semester
    semester = models.OneToOneField(
        'academia.Semester',
        on_delete=models.PROTECT,
        related_name='audit',
        verbose_name=_("Semester")
    )

    # Audit tracking
    audit_generated_at = models.DateTimeField(
        _("Audit Generated At"),
        null=True,
        blank=True,
        help_text=_("When audit entries were last synchronized")
    )

    audit_pdf = models.FileField(
        _("Audit PDF"),
        upload_to='academia/audits/',
        null=True,
        blank=True,
        validators=[
            FileExtensionValidator(allowed_extensions=['pdf']),
            validate_pdf_size
        ],
        help_text=_("Upload for the complete, signed audit report")
    )

    # Audit workflow timestamps
    audit_sent_university_at = models.DateTimeField(
        _("Audit sent to university at"),
        null=True,
        blank=True,
        help_text=_("Timestamp when audit was sent to university administration")
    )

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # History & versioning
    history = HistoricalRecords()
    version = AutoIncVersionField()

    class Meta:
        verbose_name = _("Audit Semester")
        verbose_name_plural = _("Audit Semesters")
        ordering = ['-semester__start_date']

    def __str__(self):
        return f"Audit: {self.semester.code}"

    def clean(self):
        super().clean()
        errors = {}

        # Check for duplicate semester (OneToOneField)
        if self.semester_id:
            existing = AuditSemester.objects.filter(
                semester_id=self.semester_id
            ).exclude(pk=self.pk).exists()
            
            if existing:
                errors['semester'] = _(
                    "An audit already exists for this semester."
                )

        # Check if locked via HankoSign
        if self.pk:
            original = AuditSemester.objects.get(pk=self.pk)
            st = state_snapshot(original)

            if st.get("explicit_locked"):
                errors['__all__'] = _("Audit semester is locked. Cannot modify.")

        if errors:
            raise ValidationError(errors)


class AuditEntry(models.Model):
    """
    Final audit entry for a person's ECTS allocation in a semester.

    This model represents the final calculation of ECTS entitlement,
    reimbursements, and bulk allocation for a person across all their
    roles during the semester. Generated by synchronize_audit action.
    """

    # Core relationships
    audit_semester = models.ForeignKey(
        AuditSemester,
        on_delete=models.PROTECT,
        related_name='entries',
        verbose_name=_("Audit Semester")
    )

    person = models.ForeignKey(
        Person,
        on_delete=models.PROTECT,
        related_name='audit_entries',
        verbose_name=_("Person")
    )

    # Many-to-many relationships
    person_roles = models.ManyToManyField(
        PersonRole,
        related_name='audit_entries',
        verbose_name=_("Person Roles"),
        help_text=_("All roles this person held during the semester")
    )

    inbox_requests = models.ManyToManyField(
        'academia.InboxRequest',
        blank=True,
        related_name='audit_entries',
        verbose_name=_("Inbox Requests"),
        help_text=_("Approved reimbursement requests for this person")
    )

    # Calculated ECTS
    aliquoted_ects = models.DecimalField(
        _("Aliquoted ECTS"),
        max_digits=5,
        decimal_places=2,
        help_text=_("Base ECTS with aliquotation applied (before bonus/malus)")
    )

    final_ects = models.DecimalField(
        _("Final ECTS"),
        max_digits=5,
        decimal_places=2,
        help_text=_("Final ECTS entitled (after bonus/malus)")
    )

    reimbursed_ects = models.DecimalField(
        _("Reimbursed ECTS"),
        max_digits=5,
        decimal_places=2,
        default=0,
        help_text=_("Sum of ECTS from specific course reimbursements")
    )

    remaining_ects = models.DecimalField(
        _("Remaining ECTS"),
        max_digits=5,
        decimal_places=2,
        help_text=_("Remaining ECTS credited as general (bulk)")
    )

    # Calculation transparency
    calculation_details = models.JSONField(
        _("Calculation Details"),
        default=dict,
        blank=True,
        help_text=_("Detailed breakdown of ECTS calculation per role")
    )

    # Manual review tracking
    checked_at = models.DateTimeField(
        _("Checked At"),
        null=True,
        blank=True,
        help_text=_("Timestamp when this entry was manually reviewed/edited. Protects from synchronize overwrites.")
    )

    # Manual adjustments
    notes = models.TextField(
        _("Record note"),
        blank=True,
        help_text=_("Optional notes for manual adjustments or corrections")
    )

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # History & versioning
    history = HistoricalRecords()
    version = AutoIncVersionField()

    class Meta:
        verbose_name = _("Audit Entry")
        verbose_name_plural = _("Audit Entries")
        ordering = ['person__last_name', 'person__first_name']
        constraints = [
            models.UniqueConstraint(
                fields=['audit_semester', 'person'],
                name='uq_audit_one_per_person_per_audit_semester'
            )
        ]
        indexes = [
            models.Index(fields=['audit_semester']),
            models.Index(fields=['checked_at']),
        ]

    def __str__(self):
        return f"{self.person} - {self.audit_semester.semester.code} ({self.final_ects} ECTS)"

    def clean(self):
        super().clean()
        errors = {}

        # Check for duplicate (audit_semester, person)
        if self.audit_semester_id and self.person_id:
            existing = AuditEntry.objects.filter(
                audit_semester_id=self.audit_semester_id,
                person_id=self.person_id
            ).exclude(pk=self.pk).exists()
            
            if existing:
                errors['__all__'] = _(
                    "This person already has an audit entry for this semester."
                )

        # Check if parent audit semester is locked
        if self.audit_semester_id:
            semester_st = state_snapshot(self.audit_semester)
            if semester_st.get("explicit_locked"):
                errors['__all__'] = _("Audit semester is locked. Cannot modify entries.")

        # Validate ECTS calculations
        if self.reimbursed_ects and self.reimbursed_ects < 0:
            errors['reimbursed_ects'] = _("Reimbursed ECTS cannot be negative")

        if self.remaining_ects and self.remaining_ects < 0:
            errors['remaining_ects'] = _("Remaining ECTS cannot be negative")

        if errors:
            raise ValidationError(errors)