# academia_audit/models.py
from __future__ import annotations
from django.db import models
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from simple_history.models import HistoricalRecords
from concurrency.fields import AutoIncVersionField
from hankosign.utils import state_snapshot
from people.models import PersonRole, Person


class AuditSemester(models.Model):
    """
    Audit workflow for a semester's ECTS reimbursements.

    This model manages the audit calculation and approval process
    separate from the inbox filing workflow. References the inbox
    semester and tracks the audit lifecycle.
    """

    # Reference to inbox semester
    semester = models.OneToOneField(
        'academia.Semester',
        on_delete=models.PROTECT,
        related_name='audit',
        verbose_name=_("Semester")
    )

    # Audit workflow timestamps
    audit_sent_university_at = models.DateTimeField(
        _("Audit Sent to University At"),
        null=True,
        blank=True,
        help_text=_("Timestamp when audit was sent to university administration")
    )

    # Notes
    notes = models.TextField(
        _("Notes"),
        blank=True
    )

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # History & versioning
    history = HistoricalRecords()
    version = AutoIncVersionField()

    class Meta:
        verbose_name = _("Audit Semester")
        verbose_name_plural = _("Audit Semesters")
        ordering = ['-semester__start_date']

    def __str__(self):
        return f"Audit: {self.semester.code}"

    def clean(self):
        super().clean()

        # Check if locked via HankoSign
        if self.pk:
            original = AuditSemester.objects.get(pk=self.pk)
            st = state_snapshot(original)

            if st.get("explicit_locked"):
                raise ValidationError(
                    _("Audit semester is locked. Cannot modify.")
                )


class AuditEntry(models.Model):
    """
    Final audit entry for a person's ECTS allocation in a semester.

    This model represents the final calculation of ECTS entitlement,
    reimbursements, and bulk allocation for a person across all their
    roles during the semester. Generated by synchronize_audit action.
    """

    # Core relationships
    audit_semester = models.ForeignKey(
        AuditSemester,
        on_delete=models.PROTECT,
        related_name='entries',
        verbose_name=_("Audit Semester")
    )

    person = models.ForeignKey(
        Person,
        on_delete=models.PROTECT,
        related_name='audit_entries',
        verbose_name=_("Person")
    )

    # Many-to-many relationships
    person_roles = models.ManyToManyField(
        PersonRole,
        related_name='audit_entries',
        verbose_name=_("Person Roles"),
        help_text=_("All roles this person held during the semester")
    )

    inbox_requests = models.ManyToManyField(
        'academia.InboxRequest',
        blank=True,
        related_name='audit_entries',
        verbose_name=_("Inbox Requests"),
        help_text=_("Approved reimbursement requests for this person")
    )

    # Calculated ECTS
    aliquoted_ects = models.DecimalField(
        _("Aliquoted ECTS"),
        max_digits=5,
        decimal_places=2,
        help_text=_("Base ECTS with aliquotation applied (before bonus/malus)")
    )

    final_ects = models.DecimalField(
        _("Final ECTS"),
        max_digits=5,
        decimal_places=2,
        help_text=_("Final ECTS entitled (after bonus/malus)")
    )

    reimbursed_ects = models.DecimalField(
        _("Reimbursed ECTS"),
        max_digits=5,
        decimal_places=2,
        default=0,
        help_text=_("Sum of ECTS from specific course reimbursements")
    )

    remaining_ects = models.DecimalField(
        _("Remaining ECTS"),
        max_digits=5,
        decimal_places=2,
        help_text=_("Remaining ECTS credited as general (bulk)")
    )

    # Calculation transparency
    calculation_details = models.JSONField(
        _("Calculation Details"),
        default=dict,
        blank=True,
        help_text=_("Detailed breakdown of ECTS calculation per role")
    )

    # Manual review tracking
    checked_at = models.DateTimeField(
        _("Checked At"),
        null=True,
        blank=True,
        help_text=_("Timestamp when this entry was manually reviewed/edited. Protects from synchronize overwrites.")
    )

    # Manual adjustments
    notes = models.TextField(
        _("Notes"),
        blank=True,
        help_text=_("Optional notes for manual adjustments or corrections")
    )

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # History & versioning
    history = HistoricalRecords()
    version = AutoIncVersionField()

    class Meta:
        verbose_name = _("Audit Entry")
        verbose_name_plural = _("Audit Entries")
        ordering = ['person__last_name', 'person__first_name']
        constraints = [
            models.UniqueConstraint(
                fields=['audit_semester', 'person'],
                name='uq_audit_one_per_person_per_audit_semester'
            )
        ]

    def __str__(self):
        return f"{self.person} - {self.audit_semester.semester.code} ({self.final_ects} ECTS)"

    def clean(self):
        super().clean()

        # Check if parent audit semester is locked (pseudo-child)
        if self.audit_semester_id:
            semester_st = state_snapshot(self.audit_semester)
            if semester_st.get("explicit_locked"):
                raise ValidationError(
                    _("Audit semester is locked. Cannot modify entries.")
                )

        # Validate ECTS calculations
        if self.reimbursed_ects < 0:
            raise ValidationError(
                _("Reimbursed ECTS cannot be negative")
            )

        if self.remaining_ects < 0:
            raise ValidationError(
                _("Remaining ECTS cannot be negative")
            )
