# Generated by Django 5.2.5 on 2025-11-14 19:35

import concurrency.fields
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditSemester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audit_sent_university_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when audit was sent to university administration",
                        null=True,
                        verbose_name="Audit Sent to University At",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.AutoIncVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Semester",
                "verbose_name_plural": "Audit Semesters",
                "ordering": ["-semester__start_date"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalAuditEntry",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "aliquoted_ects",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base ECTS with aliquotation applied (before bonus/malus)",
                        max_digits=5,
                        verbose_name="Aliquoted ECTS",
                    ),
                ),
                (
                    "final_ects",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Final ECTS entitled (after bonus/malus)",
                        max_digits=5,
                        verbose_name="Final ECTS",
                    ),
                ),
                (
                    "reimbursed_ects",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Sum of ECTS from specific course reimbursements",
                        max_digits=5,
                        verbose_name="Reimbursed ECTS",
                    ),
                ),
                (
                    "remaining_ects",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Remaining ECTS credited as general (bulk)",
                        max_digits=5,
                        verbose_name="Remaining ECTS",
                    ),
                ),
                (
                    "calculation_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed breakdown of ECTS calculation per role",
                        verbose_name="Calculation Details",
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this entry was manually reviewed/edited. Protects from synchronize overwrites.",
                        null=True,
                        verbose_name="Checked At",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes for manual adjustments or corrections",
                        verbose_name="Notes",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "version",
                    concurrency.fields.AutoIncVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Audit Entry",
                "verbose_name_plural": "historical Audit Entries",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAuditSemester",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "audit_sent_university_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when audit was sent to university administration",
                        null=True,
                        verbose_name="Audit Sent to University At",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "version",
                    concurrency.fields.AutoIncVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Audit Semester",
                "verbose_name_plural": "historical Audit Semesters",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aliquoted_ects",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base ECTS with aliquotation applied (before bonus/malus)",
                        max_digits=5,
                        verbose_name="Aliquoted ECTS",
                    ),
                ),
                (
                    "final_ects",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Final ECTS entitled (after bonus/malus)",
                        max_digits=5,
                        verbose_name="Final ECTS",
                    ),
                ),
                (
                    "reimbursed_ects",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Sum of ECTS from specific course reimbursements",
                        max_digits=5,
                        verbose_name="Reimbursed ECTS",
                    ),
                ),
                (
                    "remaining_ects",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Remaining ECTS credited as general (bulk)",
                        max_digits=5,
                        verbose_name="Remaining ECTS",
                    ),
                ),
                (
                    "calculation_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed breakdown of ECTS calculation per role",
                        verbose_name="Calculation Details",
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this entry was manually reviewed/edited. Protects from synchronize overwrites.",
                        null=True,
                        verbose_name="Checked At",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes for manual adjustments or corrections",
                        verbose_name="Notes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.AutoIncVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "inbox_requests",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Approved reimbursement requests for this person",
                        related_name="audit_entries",
                        to="academia.inboxrequest",
                        verbose_name="Inbox Requests",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Entry",
                "verbose_name_plural": "Audit Entries",
                "ordering": ["person__last_name", "person__first_name"],
            },
        ),
    ]
