# Generated by Django 5.2.5 on 2025-11-14 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academia", "0002_initial"),
        ("academia_audit", "0001_initial"),
        ("people", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditentry",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_entries",
                to="people.person",
                verbose_name="Person",
            ),
        ),
        migrations.AddField(
            model_name="auditentry",
            name="person_roles",
            field=models.ManyToManyField(
                help_text="All roles this person held during the semester",
                related_name="audit_entries",
                to="people.personrole",
                verbose_name="Person Roles",
            ),
        ),
        migrations.AddField(
            model_name="auditsemester",
            name="semester",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit",
                to="academia.semester",
                verbose_name="Semester",
            ),
        ),
        migrations.AddField(
            model_name="auditentry",
            name="audit_semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entries",
                to="academia_audit.auditsemester",
                verbose_name="Audit Semester",
            ),
        ),
        migrations.AddField(
            model_name="historicalauditentry",
            name="audit_semester",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="academia_audit.auditsemester",
                verbose_name="Audit Semester",
            ),
        ),
        migrations.AddField(
            model_name="historicalauditentry",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalauditentry",
            name="person",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="people.person",
                verbose_name="Person",
            ),
        ),
        migrations.AddField(
            model_name="historicalauditsemester",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalauditsemester",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="academia.semester",
                verbose_name="Semester",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditentry",
            constraint=models.UniqueConstraint(
                fields=("audit_semester", "person"),
                name="uq_audit_one_per_person_per_audit_semester",
            ),
        ),
    ]
