# Generated by Django 5.2.5 on 2025-11-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_audit', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditsemester',
            name='audit_generated_at',
            field=models.DateTimeField(blank=True, help_text='When audit entries were last synchronized', null=True, verbose_name='Audit Generated At'),
        ),
        migrations.AddField(
            model_name='auditsemester',
            name='audit_pdf',
            field=models.FileField(blank=True, help_text='Generated audit report for university', null=True, upload_to='academia/audits/', verbose_name='Audit PDF'),
        ),
        migrations.AddField(
            model_name='historicalauditsemester',
            name='audit_generated_at',
            field=models.DateTimeField(blank=True, help_text='When audit entries were last synchronized', null=True, verbose_name='Audit Generated At'),
        ),
        migrations.AddField(
            model_name='historicalauditsemester',
            name='audit_pdf',
            field=models.TextField(blank=True, help_text='Generated audit report for university', max_length=100, null=True, verbose_name='Audit PDF'),
        ),
        migrations.AlterField(
            model_name='auditsemester',
            name='audit_sent_university_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when audit was sent to university administration', null=True, verbose_name='Audit sent to university at'),
        ),
        migrations.AlterField(
            model_name='historicalauditsemester',
            name='audit_sent_university_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when audit was sent to university administration', null=True, verbose_name='Audit sent to university at'),
        ),
    ]
