# Generated by Django 5.2.5 on 2025-11-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_audit', '0003_auditsemester_audit_generated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditsemester',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='historicalauditsemester',
            name='notes',
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes for manual adjustments or corrections', verbose_name='Record note'),
        ),
        migrations.AlterField(
            model_name='historicalauditentry',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes for manual adjustments or corrections', verbose_name='Record note'),
        ),
    ]
