# Generated by Django 5.2.5 on 2025-12-08 11:54

import academia_audit.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0006_alter_historicalinboxrequest_uploaded_form_and_more'),
        ('academia_audit', '0004_remove_auditsemester_notes_and_more'),
        ('people', '0004_person_uq_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditsemester',
            name='audit_pdf',
            field=models.FileField(blank=True, help_text='Upload for the complete, signed audit report', null=True, upload_to='academia/audits/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), academia_audit.models.validate_pdf_size], verbose_name='Audit PDF'),
        ),
        migrations.AlterField(
            model_name='historicalauditsemester',
            name='audit_pdf',
            field=models.TextField(blank=True, help_text='Upload for the complete, signed audit report', max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), academia_audit.models.validate_pdf_size], verbose_name='Audit PDF'),
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['audit_semester'], name='academia_au_audit_s_21cdd0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['checked_at'], name='academia_au_checked_3aaf7a_idx'),
        ),
    ]
