# Generated by Django 5.2.5 on 2025-11-05 19:55

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='-', help_text='Shown in accordion header', max_length=200, verbose_name='Title')),
                ('author', models.CharField(blank=True, help_text='Who wrote/maintains this help page', max_length=100, verbose_name='Author')),
                ('help_contact', models.CharField(blank=True, help_text='Email or phone for questions about this area', max_length=150, verbose_name='Contact')),
                ('legend', markdownx.models.MarkdownxField(blank=True, help_text='Always visible. Explain status badges, icons, etc. Keep short!', max_length=500, verbose_name='Legend (Quick Reference)')),
                ('content', markdownx.models.MarkdownxField(default='-', help_text='Full help text. Supports Markdown formatting.', verbose_name='Help Content')),
                ('is_active', models.BooleanField(default=True, help_text='Show this help page?', verbose_name='Active')),
                ('show_legend', models.BooleanField(default=True, help_text='Display legend above the list (always visible)', verbose_name='Show Legend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.OneToOneField(help_text='Which admin page this help appears on', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Target (App + Model)')),
            ],
            options={
                'verbose_name': 'Help Page',
                'verbose_name_plural': 'Help Pages',
                'ordering': ['content_type__app_label', 'content_type__model'],
            },
        ),
    ]
