# Generated by Django 5.2.5 on 2025-11-14 19:35

import django.db.models.deletion
import markdownx.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_de",
                    models.CharField(
                        default="Hilfe", max_length=200, verbose_name="Title (German)"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        default="Help", max_length=200, verbose_name="Title (English)"
                    ),
                ),
                (
                    "author",
                    models.CharField(blank=True, max_length=100, verbose_name="Author"),
                ),
                (
                    "help_contact",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Contact"
                    ),
                ),
                (
                    "legend_de",
                    markdownx.models.MarkdownxField(
                        blank=True, default="", verbose_name="Legend (German)"
                    ),
                ),
                (
                    "legend_en",
                    markdownx.models.MarkdownxField(
                        blank=True, default="", verbose_name="Legend (English)"
                    ),
                ),
                (
                    "content_de",
                    markdownx.models.MarkdownxField(
                        default="-", verbose_name="Help Content (German)"
                    ),
                ),
                (
                    "content_en",
                    markdownx.models.MarkdownxField(
                        default="-", verbose_name="Help Content (English)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "show_legend",
                    models.BooleanField(default=True, verbose_name="Show Legend"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Target (App + Model)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Help Page",
                "verbose_name_plural": "Help Pages",
                "ordering": ["content_type__app_label", "content_type__model"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalHelpPage",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "title_de",
                    models.CharField(
                        default="Hilfe", max_length=200, verbose_name="Title (German)"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        default="Help", max_length=200, verbose_name="Title (English)"
                    ),
                ),
                (
                    "author",
                    models.CharField(blank=True, max_length=100, verbose_name="Author"),
                ),
                (
                    "help_contact",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Contact"
                    ),
                ),
                (
                    "legend_de",
                    markdownx.models.MarkdownxField(
                        blank=True, default="", verbose_name="Legend (German)"
                    ),
                ),
                (
                    "legend_en",
                    markdownx.models.MarkdownxField(
                        blank=True, default="", verbose_name="Legend (English)"
                    ),
                ),
                (
                    "content_de",
                    markdownx.models.MarkdownxField(
                        default="-", verbose_name="Help Content (German)"
                    ),
                ),
                (
                    "content_en",
                    markdownx.models.MarkdownxField(
                        default="-", verbose_name="Help Content (English)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "show_legend",
                    models.BooleanField(default=True, verbose_name="Show Legend"),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                        verbose_name="Target (App + Model)",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Help Page",
                "verbose_name_plural": "historical Help Pages",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
