# Generated by Django 5.2.5 on 2025-11-05 23:38

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('helppages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helppage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='helppage',
            name='legend',
        ),
        migrations.RemoveField(
            model_name='helppage',
            name='title',
        ),
        migrations.AddField(
            model_name='helppage',
            name='content_de',
            field=markdownx.models.MarkdownxField(default='-', help_text='Full help text in German', verbose_name='Help Content (German)'),
        ),
        migrations.AddField(
            model_name='helppage',
            name='content_en',
            field=markdownx.models.MarkdownxField(default='-', help_text='Full help text in English', verbose_name='Help Content (English)'),
        ),
        migrations.AddField(
            model_name='helppage',
            name='legend_de',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Quick reference in German', max_length=500, verbose_name='Legend (German)'),
        ),
        migrations.AddField(
            model_name='helppage',
            name='legend_en',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Quick reference in English', max_length=500, verbose_name='Legend (English)'),
        ),
        migrations.AddField(
            model_name='helppage',
            name='title_de',
            field=models.CharField(default='Hilfe', help_text='Shown in accordion header (DE)', max_length=200, verbose_name='Title (German)'),
        ),
        migrations.AddField(
            model_name='helppage',
            name='title_en',
            field=models.CharField(default='Help', help_text='Shown in accordion header (EN)', max_length=200, verbose_name='Title (English)'),
        ),
        migrations.AlterField(
            model_name='helppage',
            name='author',
            field=models.CharField(blank=True, max_length=100, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='helppage',
            name='content_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Target (App + Model)'),
        ),
        migrations.AlterField(
            model_name='helppage',
            name='help_contact',
            field=models.CharField(blank=True, max_length=150, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='helppage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='helppage',
            name='show_legend',
            field=models.BooleanField(default=True, verbose_name='Show Legend'),
        ),
    ]
