# Generated by Django 5.2.5 on 2025-11-06 00:21

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helppages', '0002_remove_helppage_content_remove_helppage_legend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helppage',
            name='content_de',
            field=markdownx.models.MarkdownxField(default='-', verbose_name='Help Content (German)'),
        ),
        migrations.AlterField(
            model_name='helppage',
            name='content_en',
            field=markdownx.models.MarkdownxField(default='-', verbose_name='Help Content (English)'),
        ),
        migrations.AlterField(
            model_name='helppage',
            name='legend_de',
            field=markdownx.models.MarkdownxField(blank=True, default='', verbose_name='Legend (German)'),
        ),
        migrations.AlterField(
            model_name='helppage',
            name='legend_en',
            field=markdownx.models.MarkdownxField(blank=True, default='', verbose_name='Legend (English)'),
        ),
        migrations.AlterField(
            model_name='helppage',
            name='title_de',
            field=models.CharField(default='Hilfe', max_length=200, verbose_name='Title (German)'),
        ),
        migrations.AlterField(
            model_name='helppage',
            name='title_en',
            field=models.CharField(default='Help', max_length=200, verbose_name='Title (English)'),
        ),
    ]
