# Generated by Django 5.2.5 on 2025-11-14 19:35

import concurrency.fields
import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalSemester",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Short code in format WS## or SS## (e.g., WS24, SS25)",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Code must be in format: WS## or SS## (e.g., WS24, SS25)",
                                regex="^(WS|SS)\\d{2}$",
                            )
                        ],
                        verbose_name="Code",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Full name, e.g., Winter Semester 2024/25",
                        max_length=100,
                        verbose_name="Display Name",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                (
                    "filing_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="When public filing platform opens for new requests",
                        null=True,
                        verbose_name="Filing Start",
                    ),
                ),
                (
                    "filing_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="When public filing platform closes for new requests",
                        null=True,
                        verbose_name="Filing End",
                    ),
                ),
                (
                    "access_password",
                    models.CharField(
                        blank=True,
                        help_text="Password for public filing access (auto-generated)",
                        max_length=50,
                        verbose_name="Access Password",
                    ),
                ),
                (
                    "ects_adjustment",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Bonus/malus ECTS (e.g., +2 or -2) for elected roles",
                        max_digits=3,
                        verbose_name="ECTS Adjustment",
                    ),
                ),
                (
                    "audit_generated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When audit entries were last synchronized",
                        null=True,
                        verbose_name="Audit Generated At",
                    ),
                ),
                (
                    "audit_pdf",
                    models.TextField(
                        blank=True,
                        help_text="Generated audit report for university",
                        max_length=100,
                        null=True,
                        verbose_name="Audit PDF",
                    ),
                ),
                (
                    "audit_sent_university_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When audit was sent to university",
                        null=True,
                        verbose_name="Sent to University At",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "version",
                    concurrency.fields.AutoIncVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Semester",
                "verbose_name_plural": "historical Semesters",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="InboxCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_code",
                    models.CharField(
                        blank=True,
                        help_text="Course code, e.g., LV101",
                        max_length=20,
                        verbose_name="Course Code",
                    ),
                ),
                (
                    "course_name",
                    models.CharField(
                        blank=True,
                        help_text="Full course name, e.g., Advanced Mathematics",
                        max_length=200,
                        verbose_name="Course Name",
                    ),
                ),
                (
                    "ects_amount",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="ECTS credit for this course",
                        max_digits=3,
                        verbose_name="ECTS Amount",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="InboxRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        blank=True,
                        help_text="Unique code for student to access their request",
                        max_length=20,
                        unique=True,
                        verbose_name="Reference Code",
                    ),
                ),
                (
                    "submission_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which request was submitted (audit trail)",
                        null=True,
                        verbose_name="Submission IP",
                    ),
                ),
                (
                    "student_note",
                    models.TextField(
                        blank=True,
                        help_text="Optional note from student",
                        verbose_name="Student Note",
                    ),
                ),
                (
                    "affidavit1_confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When student confirmed initial submission affidavit",
                        null=True,
                        verbose_name="Affidavit 1 Confirmed At",
                    ),
                ),
                (
                    "affidavit2_confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When student confirmed form upload affidavit",
                        null=True,
                        verbose_name="Affidavit 2 Confirmed At",
                    ),
                ),
                (
                    "uploaded_form",
                    models.FileField(
                        blank=True,
                        help_text="Signed form with professor signatures",
                        null=True,
                        upload_to="academia/forms/%Y/%m/",
                        verbose_name="Uploaded Form",
                    ),
                ),
                (
                    "uploaded_form_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Uploaded Form At"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.AutoIncVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
            ],
            options={
                "verbose_name": "Inbox Request",
                "verbose_name_plural": "Inbox Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code in format WS## or SS## (e.g., WS24, SS25)",
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Code must be in format: WS## or SS## (e.g., WS24, SS25)",
                                regex="^(WS|SS)\\d{2}$",
                            )
                        ],
                        verbose_name="Code",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Full name, e.g., Winter Semester 2024/25",
                        max_length=100,
                        verbose_name="Display Name",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                (
                    "filing_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="When public filing platform opens for new requests",
                        null=True,
                        verbose_name="Filing Start",
                    ),
                ),
                (
                    "filing_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="When public filing platform closes for new requests",
                        null=True,
                        verbose_name="Filing End",
                    ),
                ),
                (
                    "access_password",
                    models.CharField(
                        blank=True,
                        help_text="Password for public filing access (auto-generated)",
                        max_length=50,
                        verbose_name="Access Password",
                    ),
                ),
                (
                    "ects_adjustment",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Bonus/malus ECTS (e.g., +2 or -2) for elected roles",
                        max_digits=3,
                        verbose_name="ECTS Adjustment",
                    ),
                ),
                (
                    "audit_generated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When audit entries were last synchronized",
                        null=True,
                        verbose_name="Audit Generated At",
                    ),
                ),
                (
                    "audit_pdf",
                    models.FileField(
                        blank=True,
                        help_text="Generated audit report for university",
                        null=True,
                        upload_to="academia/audits/",
                        verbose_name="Audit PDF",
                    ),
                ),
                (
                    "audit_sent_university_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When audit was sent to university",
                        null=True,
                        verbose_name="Sent to University At",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.AutoIncVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
            ],
            options={
                "verbose_name": "Semester",
                "verbose_name_plural": "Semesters",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalInboxRequest",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Unique code for student to access their request",
                        max_length=20,
                        verbose_name="Reference Code",
                    ),
                ),
                (
                    "submission_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which request was submitted (audit trail)",
                        null=True,
                        verbose_name="Submission IP",
                    ),
                ),
                (
                    "student_note",
                    models.TextField(
                        blank=True,
                        help_text="Optional note from student",
                        verbose_name="Student Note",
                    ),
                ),
                (
                    "affidavit1_confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When student confirmed initial submission affidavit",
                        null=True,
                        verbose_name="Affidavit 1 Confirmed At",
                    ),
                ),
                (
                    "affidavit2_confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When student confirmed form upload affidavit",
                        null=True,
                        verbose_name="Affidavit 2 Confirmed At",
                    ),
                ),
                (
                    "uploaded_form",
                    models.TextField(
                        blank=True,
                        help_text="Signed form with professor signatures",
                        max_length=100,
                        null=True,
                        verbose_name="Uploaded Form",
                    ),
                ),
                (
                    "uploaded_form_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Uploaded Form At"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "version",
                    concurrency.fields.AutoIncVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Inbox Request",
                "verbose_name_plural": "historical Inbox Requests",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
