# Generated by Django 5.2.5 on 2025-11-14 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academia", "0001_initial"),
        ("people", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinboxrequest",
            name="person_role",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The role under which ECTS are being claimed",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="people.personrole",
                verbose_name="Person Role",
            ),
        ),
        migrations.AddField(
            model_name="historicalsemester",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inboxrequest",
            name="person_role",
            field=models.ForeignKey(
                help_text="The role under which ECTS are being claimed",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ects_requests",
                to="people.personrole",
                verbose_name="Person Role",
            ),
        ),
        migrations.AddField(
            model_name="inboxcourse",
            name="inbox_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="academia.inboxrequest",
                verbose_name="Inbox Request",
            ),
        ),
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="ck_semester_dates",
            ),
        ),
        migrations.AddField(
            model_name="inboxrequest",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inbox_requests",
                to="academia.semester",
                verbose_name="Semester",
            ),
        ),
        migrations.AddField(
            model_name="historicalinboxrequest",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="academia.semester",
                verbose_name="Semester",
            ),
        ),
        migrations.AddConstraint(
            model_name="inboxrequest",
            constraint=models.UniqueConstraint(
                fields=("person_role", "semester"),
                name="uq_inbox_one_per_person_per_semester",
            ),
        ),
    ]
