# Generated by Django 5.2.5 on 2025-11-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academia", "0001_initial"),
        ("people", "0027_remove_historicalpersonrole_confirm_ref_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsemester",
            name="filing_end",
            field=models.DateTimeField(
                blank=True,
                help_text="When public filing platform closes for new requests",
                null=True,
                verbose_name="Filing End",
            ),
        ),
        migrations.AddField(
            model_name="historicalsemester",
            name="filing_start",
            field=models.DateTimeField(
                blank=True,
                help_text="When public filing platform opens for new requests",
                null=True,
                verbose_name="Filing Start",
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="filing_end",
            field=models.DateTimeField(
                blank=True,
                help_text="When public filing platform closes for new requests",
                null=True,
                verbose_name="Filing End",
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="filing_start",
            field=models.DateTimeField(
                blank=True,
                help_text="When public filing platform opens for new requests",
                null=True,
                verbose_name="Filing Start",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsemester",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="DEPRECATED: Use filing_start/filing_end instead",
                verbose_name="Active for Filing",
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="DEPRECATED: Use filing_start/filing_end instead",
                verbose_name="Active for Filing",
            ),
        ),
        migrations.AlterField(
            model_name="semesterauditentry",
            name="inbox_requests",
            field=models.ManyToManyField(
                blank=True,
                help_text="Approved reimbursement requests for this person (DEPRECATED)",
                related_name="semester_audit_entries",
                to="academia.inboxrequest",
                verbose_name="Inbox Requests",
            ),
        ),
        migrations.AlterField(
            model_name="semesterauditentry",
            name="person_roles",
            field=models.ManyToManyField(
                help_text="All roles this person held during the semester (DEPRECATED)",
                related_name="semester_audit_entries",
                to="people.personrole",
                verbose_name="Person Roles",
            ),
        ),
    ]
