# Generated by Django 5.2.5 on 2025-11-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academia", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinboxrequest",
            name="filing_source",
            field=models.CharField(
                choices=[("PUBLIC", "Public Portal"), ("ADMIN", "Admin Interface")],
                default="ADMIN",
                help_text="How this request was created (public portal or admin)",
                max_length=20,
                verbose_name="Filing Source",
            ),
        ),
        migrations.AddField(
            model_name="inboxrequest",
            name="filing_source",
            field=models.CharField(
                choices=[("PUBLIC", "Public Portal"), ("ADMIN", "Admin Interface")],
                default="ADMIN",
                help_text="How this request was created (public portal or admin)",
                max_length=20,
                verbose_name="Filing Source",
            ),
        ),
    ]
