# Generated by Django 5.2.5 on 2025-11-13 01:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_historicalsemester_filing_end_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
        model_name='semesterauditentry',
        name='uq_audit_one_per_person_per_semester',
         ),
        migrations.RemoveField(
            model_name='semesterauditentry',
            name='inbox_requests',
        ),
        migrations.RemoveField(
            model_name='semesterauditentry',
            name='person',
        ),
        migrations.RemoveField(
            model_name='semesterauditentry',
            name='person_roles',
        ),
        migrations.RemoveField(
            model_name='semesterauditentry',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='historicalsemester',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='historicalsemester',
            name='code',
            field=models.CharField(db_index=True, help_text='Short code in format WS## or SS## (e.g., WS24, SS25)', max_length=10, validators=[django.core.validators.RegexValidator(message='Code must be in format: WS## or SS## (e.g., WS24, SS25)', regex='^(WS|SS)\\d{2}$')], verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='code',
            field=models.CharField(help_text='Short code in format WS## or SS## (e.g., WS24, SS25)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Code must be in format: WS## or SS## (e.g., WS24, SS25)', regex='^(WS|SS)\\d{2}$')], verbose_name='Code'),
        ),
        migrations.DeleteModel(
            name='HistoricalSemesterAuditEntry',
        ),
        migrations.DeleteModel(
            name='SemesterAuditEntry',
        ),
    ]
