# Generated by Django 5.2.5 on 2025-11-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_historicalinboxrequest_filing_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinboxrequest',
            name='stage',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('TRANSFERRED', 'Transferred to Audit')], default='DRAFT', help_text='Current workflow stage. Auto-computed from HankoSign signatures.', max_length=12, verbose_name='Stage'),
        ),
        migrations.AddField(
            model_name='inboxrequest',
            name='stage',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('TRANSFERRED', 'Transferred to Audit')], default='DRAFT', help_text='Current workflow stage. Auto-computed from HankoSign signatures.', max_length=12, verbose_name='Stage'),
        ),
    ]
