# Generated by Django 5.2.5 on 2025-11-23 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_historicalinboxrequest_stage_inboxrequest_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsemester',
            name='audit_generated_at',
        ),
        migrations.RemoveField(
            model_name='historicalsemester',
            name='audit_pdf',
        ),
        migrations.RemoveField(
            model_name='historicalsemester',
            name='audit_sent_university_at',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='audit_generated_at',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='audit_pdf',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='audit_sent_university_at',
        ),
    ]
