# Generated by Django 5.2.5 on 2025-12-08 11:12

import academia.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0005_remove_historicalsemester_audit_generated_at_and_more'),
        ('people', '0004_person_uq_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinboxrequest',
            name='uploaded_form',
            field=models.TextField(blank=True, help_text='Signed form with professor signatures', max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), academia.models.validate_file_size], verbose_name='Uploaded Form'),
        ),
        migrations.AlterField(
            model_name='inboxrequest',
            name='uploaded_form',
            field=models.FileField(blank=True, help_text='Signed form with professor signatures', null=True, upload_to='academia/forms/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), academia.models.validate_file_size], verbose_name='Uploaded Form'),
        ),
        migrations.AddIndex(
            model_name='inboxrequest',
            index=models.Index(fields=['stage'], name='academia_in_stage_6050bb_idx'),
        ),
        migrations.AddIndex(
            model_name='inboxrequest',
            index=models.Index(fields=['semester', 'stage'], name='academia_in_semeste_092d6a_idx'),
        ),
        migrations.AddIndex(
            model_name='inboxrequest',
            index=models.Index(fields=['-created_at'], name='academia_in_created_8add9b_idx'),
        ),
    ]
