"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rz9r+bbkq_y+p&y&$m98m()h+b2g4n4eedn4c*h51zzzntna*h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

LOGIN_URL = "/admin/login/"
LOGIN_REDIRECT_URL = "/admin/"


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'simple_history',
    'django_object_actions',
    'django_renderpdf',

    'people',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-gb'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ("en", "English"),
    ("de", "Deutsch"),
]

from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent
LOCALE_PATHS = [BASE_DIR / "locale"]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    # Branding
    "site_title": "UniHanko Back Office",
    "site_header": "UniHanko Administration",
    "site_brand": "UniHanko",
    "welcome_sign": "Welcome to UniHanko Back Office",
    "site_logo": "img/unihanko-logo.svg",            # put these under STATIC
    "login_logo": "img/unihanko-mark.svg",           # optional second logo for login
    "site_logo_classes": "img-fluid",

    # Quick nav
    "topmenu_links": [
        {"name": "Onboarding",  "url": "/admin/people/personrole/add/",       "permissions": ["people.add_personrole"]},
        {"name": "Offboarding", "url": "/admin/people/personrole/?active=1",  "permissions": ["people.change_personrole"]},
        # examples you can add later:
        # {"app": "people"},                               # jump to the Personnel section
        # {"name": "Public site", "url": "/", "new_window": True},
    ],
    "usermenu_links": [
        # {"model": "auth.user"},                         # profile
        # {"name": "Help", "url": "https://…", "new_window": True},
    ],

    # Icons (Font Awesome 5/6)
    "icons": {
        "people": "fa-solid fa-users-gear",                 # app icon (Personnel)
        "people.Person": "fa-solid fa-user",
        "people.PersonRole": "fa-solid fa-user-check",
        "people.Role": "fa-solid fa-id-badge",
        "people.RoleTransitionReason": "fa-solid fa-flag",
    },

    # Sidebar ordering within the app
    "order_with_respect_to": {
        "people": ["PersonRole", "Person", "RoleTransitionReason", "Role"],
    },

    # Hide historical models from menu
    "hide_models": [
        "people.HistoricalPerson",
        "people.HistoricalRole",
        "people.HistoricalPersonRole",
        "people.HistoricalRoleTransitionReason",
    ],

    # Quality of life
    "related_modal_active": True,                    # add related objects in a modal
    "changeform_format": "vertical_tabs",            # or "horizontal_tabs" / "collapsible"
    "changeform_format_overrides": {
        "people.person": "collapsible",              # example: person edit as collapsible
    },
    "language_chooser": True,                       # header language switcher

    # Custom assets
    "custom_css": "admin/unihanko.css",
    "custom_js":  None,

    # Optional: show Jazzmin UI builder (handy for experimenting)
    # "show_ui_builder": True,
}

JAZZMIN_UI_TWEAKS = {
    # Bootswatch theme names: flatly, simplex, cosmo, lumen, slate, darkly, etc.
    "theme": "flatly",
    "dark_mode_theme": "darkly",

    # Navbar / sidebar styling
    "navbar": "navbar-dark bg-primary",
    "no_navbar_border": True,
    "brand_small_text": False,
    "navbar_small_text": False,

    "sidebar": "sidebar-dark-primary",              # or "sidebar-light-primary"
    "sidebar_nav_small_text": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_disable_expand": False,

    # Typography
    "body_small_text": False,
    "footer_small_text": False,
}

