"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# File: config/settings.py
# Version: 1.0.3
# Author: vas
# Modified: 2025-12-08

import environ
from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Environment variables
env = environ.Env(
    DEBUG=(bool, False) # default to false for safety
)
environ.Env.read_env(BASE_DIR / '.env')

# UniHanko version
UNIHANKO_VERSION = "1.0.0"
UNIHANKO_CODENAME = "Sakura"
UNIHANKO_VERSION_FULL = f"v{UNIHANKO_VERSION} \"{UNIHANKO_CODENAME}\""
# Environment indicator (tracks deployment)
ENVIRONMENT = env('ENVIRONMENT', default='development')
DEBUG = env.bool('DEBUG', default=False)
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])
LOGIN_URL = "/admin/login/"
LOGIN_REDIRECT_URL = "/admin/"

# Fail loudly if secrets not set in production
if not DEBUG:
    SECRET_KEY = env('SECRET_KEY')  # No default - raises error if missing
    HANKOSIGN_SECRET = env('HANKOSIGN_SECRET')
else:
    # Development: allow defaults
    SECRET_KEY = env('SECRET_KEY', default='django-insecure-rz9r+bbkq_y+p&y&$m98m()h+b2g4n4eedn4c*h51zzzntna*h')
    HANKOSIGN_SECRET = env('HANKOSIGN_SECRET', default='django-insecure-GENERATE_ANOTHER_ONE_HERE')

if DEBUG:
    # Development: logs in project directory
    LOGS_DIR = BASE_DIR / 'logs'
    # Development: can bootstrap from repo fixtures (convenience)
    BOOTSTRAP_DATA_DIR = BASE_DIR / 'config' / 'fixtures'
else:
    # Production/Staging ('Suupu'): Docker mount
    LOGS_DIR = Path('/var/log/unihanko')
    # Production: sensitive bootstrap data from mount (never in repo)
    BOOTSTRAP_DATA_DIR = Path('/mnt/bootstrap-data')
    BOOTSTRAP_DATA_DIR.mkdir(parents=True, exist_ok=True)

# Ensure directory exists
LOGS_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        # Console output (always on)
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        
        # General Django logs
        'file_django': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django.log',
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        
        # Authentication events
        'file_auth': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'auth.log',
            'maxBytes': 5 * 1024 * 1024,  # 5MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        
        # HankoSign workflow state changes
        'file_hankosign': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'hankosign.log',
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        
        # Payment plan modifications
        'file_payments': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'payments.log',
            'maxBytes': 5 * 1024 * 1024,  # 5MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        
        # Admin actions (deletions, bulk actions, sensitive ops)
        'file_admin': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'admin.log',
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        
        # Errors and exceptions
        'file_errors': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'errors.log',
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 10,  # Keep more error logs
            'formatter': 'verbose',
        },
    },
    'loggers': {
        # Root Django logger - catches all Django internals
        'django': {
            'handlers': ['console', 'file_django'],
            'level': 'INFO',
            'propagate': False,
        },
        
        # Django request/response logs
        'django.request': {
            'handlers': ['console', 'file_errors'],
            'level': 'ERROR',  # Only log request errors (4xx, 5xx)
            'propagate': False,
        },
        
        # Database queries (useful for debugging, disable in prod)
        'django.db.backends': {
            'handlers': ['console'] if DEBUG else [],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        
        # Authentication events
        'unihanko.auth': {
            'handlers': ['console', 'file_auth'],
            'level': 'INFO',
            'propagate': False,
        },
        
        # HankoSign workflow
        'unihanko.hankosign': {
            'handlers': ['console', 'file_hankosign'],
            'level': 'INFO',
            'propagate': False,
        },
        
        # Payment plans
        'unihanko.payments': {
            'handlers': ['console', 'file_payments'],
            'level': 'INFO',
            'propagate': False,
        },
        
        # Admin actions
        'unihanko.admin': {
            'handlers': ['console', 'file_admin'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'concurrency',
    'solo',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',
    'markdownx',
    'tinymce',
    'helppages',
    'import_export',
    'simple_history',
    'django_object_actions',
    'django_renderpdf',
    'adminsortable2',
    'captcha',
    'django_admin_inline_paginator_plus',
    'axes',

    'core',
    'annotations',
    'hankosign',
    'people',
    'finances',
    'employees',
    'assembly',
    'academia',
    'academia_audit',
    'portal',

    'organisation',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'core.middleware.ConstraintErrorMiddleware',
    'core.middleware.MaintenanceModeMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]
SITE_ID = 1
ROOT_URLCONF = 'config.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.version_info',
            ],
        },
    },
]
WSGI_APPLICATION = 'config.wsgi.application'

# Security settings for production (behind Caddy reverse proxy)
if not DEBUG:
    # Proxy configuration - CRITICAL
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # ^ Tells Django to trust Caddy's X-Forwarded-Proto header
    
    # DO NOT SET SECURE_SSL_REDIRECT = True
    # Caddy already handles HTTP→HTTPS redirect, and Django only sees HTTP internally
    # Setting this would cause infinite redirects!
    
    # Cookie Security - CRITICAL (these are about cookie flags, not transport)
    SESSION_COOKIE_SECURE = True  # Browser only sends cookie over HTTPS
    CSRF_COOKIE_SECURE = True     # Browser only sends CSRF token over HTTPS
    SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access
    CSRF_COOKIE_HTTPONLY = True     # Prevent JavaScript access
    SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection
    CSRF_COOKIE_SAMESITE = 'Lax'     # CSRF protection
    CSRF_COOKIE_AGE = 31449600  # 1 year
    
    # Content Security - STILL USEFUL
    SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME sniffing
    SECURE_BROWSER_XSS_FILTER = True    # Enable XSS filter
    
    # HSTS - OPTIONAL (Caddy can set these headers instead)
    # If Caddy sets HSTS headers, these are redundant but harmless
    SECURE_HSTS_SECONDS = 31536000  
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Session Security
    SESSION_COOKIE_AGE = 86400  # 24 hours
    SESSION_SAVE_EVERY_REQUEST = True
    
    # CSRF trusted origins - CRITICAL
    CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])
    if not CSRF_TRUSTED_ORIGINS:
        raise ValueError(
            "CSRF_TRUSTED_ORIGINS must be set in production .env file. "
            "Example: CSRF_TRUSTED_ORIGINS=https://unihanko.example.com"
        )
else:
    # Development settings
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_AGE = 1209600  # 2 weeks


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': env('DB_ENGINE', default='django.db.backends.sqlite3'),
        'NAME': env('DB_NAME', default=str(BASE_DIR / 'db.sqlite3')),
        'USER': env('DB_USER', default=''),
        'PASSWORD': env('DB_PASSWORD', default=''),
        'HOST': env('DB_HOST', default=''),
        'PORT': env('DB_PORT', default=''),
        'CONN_MAX_AGE': env.int('DB_CONN_MAX_AGE', default=600) if not DEBUG else 0,  # 10 min pool
        'OPTIONS': {
            'connect_timeout': 10,
        } if not DEBUG else {},
    }
}

# Admin session timeout (shorter than regular users)
if not DEBUG:
    ADMIN_SESSION_COOKIE_AGE = 14400  # 4 hours for admin sessions

# Axes configuration
AXES_FAILURE_LIMIT = 5  # Lock after 5 failed attempts
AXES_COOLOFF_TIME = 1  # 1 hour lockout
AXES_LOCKOUT_PARAMETERS = [
    'username',
    'ip_address',
]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-gb'
X_FRAME_OPTIONS = "SAMEORIGIN"
TIME_ZONE = 'Europe/Vienna'
USE_I18N = True
USE_TZ = True
LANGUAGES = [
    ("en", "English"),
    ("de", "Deutsch"),
]
LOCALE_PATHS = [BASE_DIR / "locale"]
if DEBUG:
    INSTALLED_APPS += ['rosetta']
    from .settings_rosetta import DEEPL_AUTH_KEY, ROSETTA_ENABLE_TRANSLATION_SUGGESTIONS

# markdown configuration
MARKDOWNX_MARKDOWN_EXTENSIONS = [
    'markdown.extensions.extra',
    'markdown.extensions.nl2br',
    'markdown.extensions.sane_lists',
]
MARKDOWNX_MARKDOWN_EXTENSION_CONFIGS = {}
MARKDOWNX_MEDIA_PATH = 'markdownx/'


# TinyMCE configuration (simple WYSIWYG for protocol fields)
TINYMCE_DEFAULT_CONFIG = {
    'height': 360,
    'width': '100%',
    'menubar': False,
    'plugins': 'lists link',
    'toolbar': 'undo redo | bold italic underline | bullist numlist | removeformat',
    'statusbar': False,
    'branding': False,
    'content_style': 'body { font-family: Arial, sans-serif; font-size: 14px; }',
    'license_key': 'gpl',
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Where collectstatic puts files

if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# Media files configuration
MEDIA_URL = '/media/'

if DEBUG:
    # Development: Use local filesystem
    MEDIA_ROOT = BASE_DIR / 'media'
else:
    # Production/Staging: Use MinIO
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
    
    AWS_ACCESS_KEY_ID = env('MINIO_ACCESS_KEY')
    AWS_SECRET_ACCESS_KEY = env('MINIO_SECRET_KEY')
    AWS_STORAGE_BUCKET_NAME = env('MINIO_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = env('MINIO_ENDPOINT_URL')
    AWS_S3_REGION_NAME = 'us-east-1'  # MinIO default, always this
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = 3600  # 1 hour signed URLs

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# django-simple-captcha configuration
CAPTCHA_IMAGE_SIZE = (120, 50)
CAPTCHA_FONT_SIZE = 32
CAPTCHA_LETTER_ROTATION = (-20, 20)
CAPTCHA_BACKGROUND_COLOR = '#0a0a0a'
CAPTCHA_FOREGROUND_COLOR = '#FF6B35'
CAPTCHA_NOISE_FUNCTIONS = ('captcha.helpers.noise_dots',)
CAPTCHA_LENGTH = 4  # Number of characters
CAPTCHA_TIMEOUT = 5  # Minutes

#jazzmin configuration
from .settings_jazzmin import JAZZMIN_SETTINGS, JAZZMIN_UI_TWEAKS


