# Generated by Django 5.2.5 on 2025-11-13 04:59

import concurrency.fields
import django.core.validators
import django.db.models.deletion
import re
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assembly', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleTransitionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Stable code like I01, O01, C99 OR X99 (to be reserved for 'Other').", max_length=4, unique=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='Use I## / O## / C## or X99 for Other.', regex='^(?:[IOC]\\d{2}|X99)$')], verbose_name='Code')),
                ('name', models.CharField(help_text='German label/name for the reason given (e.g. Eintritt, Austritt, ...).', max_length=120, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, help_text='Optional English label/name for the reason given.', max_length=120, verbose_name='Name (EN)')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Reason',
                'verbose_name_plural': 'Reasons',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPerson',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Stable system identifier.', verbose_name='UUID')),
                ('first_name', models.CharField(max_length=80, verbose_name='First name')),
                ('last_name', models.CharField(max_length=80, verbose_name='Last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('student_email', models.EmailField(blank=True, max_length=254, verbose_name='Student email')),
                ('matric_no', models.CharField(blank=True, help_text='Example FH: s2210562023 — federal: 52103904', max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Use 's' + 10 digits (FH) or up to 10 digits (federal).", regex='^([sS]\\d{9,10}|\\d{1,10})$')], verbose_name='Matriculation number')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('D', 'Diverse'), ('X', 'Not specified')], default='X', max_length=1, verbose_name='Gender')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('personal_access_code', models.CharField(blank=True, db_index=True, help_text='To be shared with personnel for certain public filing systems (FuGeb etc.).', max_length=19, verbose_name='Personal access code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated at')),
                ('version', concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='Link to a Django user account (optional).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Account')),
            ],
            options={
                'verbose_name': 'historical Person',
                'verbose_name_plural': 'historical People',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRole',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                ('short_name', models.CharField(blank=True, help_text='Role short-form', max_length=20, validators=[django.core.validators.RegexValidator(message='Format: no digits, max. 20 characters, e.g. WiRef', regex='^\\D{1,20}$')], verbose_name='Short form')),
                ('ects_cap', models.DecimalField(decimal_places=1, default=0, help_text='The nominal reimbursible ECTS amount assigned to the role re: MOU with the academic board', max_digits=4, verbose_name='ECTS cap')),
                ('is_elected', models.BooleanField(default=False, help_text='Whether this role is elected via an election authority re: HSG 2014', verbose_name='Elected position')),
                ('kind', models.CharField(choices=[('DEPT. HEAD', 'Department head (Referent:in)'), ('DEPT. CLERK', 'Department clerk (Sachbearbeiter:in)'), ('OTHER', 'Other / miscellaneous')], db_index=True, default='OTHER', help_text='Type of role within the (legal) personnel structure.', max_length=16, verbose_name='Role type')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_stipend_reimbursed', models.BooleanField(default=False, help_text='Whether this role is ordinarily reimbursed via stipend [FuGeb]', verbose_name='Reimbursed via stipend')),
                ('is_system', models.BooleanField(default=False, help_text='Internal/admin role. Ignores stipend/ECTS expectations and is treated separately in policies.', verbose_name='System role')),
                ('default_monthly_amount', models.DecimalField(blank=True, decimal_places=2, help_text='default monthly pay (if eligible) per Statutes', max_digits=10, null=True, verbose_name='Default monthly stipend')),
                ('version', concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Role',
                'verbose_name_plural': 'historical Roles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable system identifier.', unique=True, verbose_name='UUID')),
                ('first_name', models.CharField(max_length=80, verbose_name='First name')),
                ('last_name', models.CharField(max_length=80, verbose_name='Last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('student_email', models.EmailField(blank=True, max_length=254, verbose_name='Student email')),
                ('matric_no', models.CharField(blank=True, help_text='Example FH: s2210562023 — federal: 52103904', max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Use 's' + 10 digits (FH) or up to 10 digits (federal).", regex='^([sS]\\d{9,10}|\\d{1,10})$')], verbose_name='Matriculation number')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('D', 'Diverse'), ('X', 'Not specified')], default='X', max_length=1, verbose_name='Gender')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('personal_access_code', models.CharField(blank=True, help_text='To be shared with personnel for certain public filing systems (FuGeb etc.).', max_length=19, unique=True, verbose_name='Personal access code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('version', concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number')),
                ('user', models.OneToOneField(blank=True, help_text='Link to a Django user account (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL, verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('short_name', models.CharField(blank=True, help_text='Role short-form', max_length=20, validators=[django.core.validators.RegexValidator(message='Format: no digits, max. 20 characters, e.g. WiRef', regex='^\\D{1,20}$')], verbose_name='Short form')),
                ('ects_cap', models.DecimalField(decimal_places=1, default=0, help_text='The nominal reimbursible ECTS amount assigned to the role re: MOU with the academic board', max_digits=4, verbose_name='ECTS cap')),
                ('is_elected', models.BooleanField(default=False, help_text='Whether this role is elected via an election authority re: HSG 2014', verbose_name='Elected position')),
                ('kind', models.CharField(choices=[('DEPT. HEAD', 'Department head (Referent:in)'), ('DEPT. CLERK', 'Department clerk (Sachbearbeiter:in)'), ('OTHER', 'Other / miscellaneous')], db_index=True, default='OTHER', help_text='Type of role within the (legal) personnel structure.', max_length=16, verbose_name='Role type')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_stipend_reimbursed', models.BooleanField(default=False, help_text='Whether this role is ordinarily reimbursed via stipend [FuGeb]', verbose_name='Reimbursed via stipend')),
                ('is_system', models.BooleanField(default=False, help_text='Internal/admin role. Ignores stipend/ECTS expectations and is treated separately in policies.', verbose_name='System role')),
                ('default_monthly_amount', models.DecimalField(blank=True, decimal_places=2, help_text='default monthly pay (if eligible) per Statutes', max_digits=10, null=True, verbose_name='Default monthly stipend')),
                ('version', concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('is_system', True), _negated=True), ('kind', 'OTHER'), _connector='OR'), name='ck_system_kind_other')],
            },
        ),
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('effective_start', models.DateField(blank=True, null=True, verbose_name='Effective start')),
                ('effective_end', models.DateField(blank=True, null=True, verbose_name='Effective end')),
                ('confirm_date', models.DateField(blank=True, help_text='Date of assembly confirmation (if applicable)', null=True, verbose_name='Confirmation date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('version', concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('elected_via', models.ForeignKey(blank=True, help_text='Assembly session item that confirmed this appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elected_persons', to='assembly.sessionitem', verbose_name='Elected via')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='people.person', verbose_name='Person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='people.role', verbose_name='Role')),
                ('end_reason', models.ForeignKey(blank=True, help_text='Why this assignment ended (e.g. Austritt). Required when an end date is set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_ended', to='people.roletransitionreason', verbose_name='End reason')),
                ('start_reason', models.ForeignKey(blank=True, help_text='Why this assignment started (e.g. Eintritt).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_started', to='people.roletransitionreason', verbose_name='Start reason')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPersonRole',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('effective_start', models.DateField(blank=True, null=True, verbose_name='Effective start')),
                ('effective_end', models.DateField(blank=True, null=True, verbose_name='Effective end')),
                ('confirm_date', models.DateField(blank=True, help_text='Date of assembly confirmation (if applicable)', null=True, verbose_name='Confirmation date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('version', concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('elected_via', models.ForeignKey(blank=True, db_constraint=False, help_text='Assembly session item that confirmed this appointment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assembly.sessionitem', verbose_name='Elected via')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.person', verbose_name='Person')),
                ('role', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.role', verbose_name='Role')),
                ('end_reason', models.ForeignKey(blank=True, db_constraint=False, help_text='Why this assignment ended (e.g. Austritt). Required when an end date is set.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.roletransitionreason', verbose_name='End reason')),
                ('start_reason', models.ForeignKey(blank=True, db_constraint=False, help_text='Why this assignment started (e.g. Eintritt).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.roletransitionreason', verbose_name='Start reason')),
            ],
            options={
                'verbose_name': 'historical Assignment',
                'verbose_name_plural': 'historical Assignments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['last_name', 'first_name'], name='people_pers_last_na_c63c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['matric_no'], name='people_pers_matric__87e6f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('matric_no__isnull', False)), fields=('matric_no',), name='uq_person_matric_no'),
        ),
        migrations.AddIndex(
            model_name='personrole',
            index=models.Index(fields=['effective_start'], name='people_pers_effecti_7814bf_idx'),
        ),
        migrations.AddIndex(
            model_name='personrole',
            index=models.Index(fields=['effective_end'], name='people_pers_effecti_93522b_idx'),
        ),
        migrations.AddIndex(
            model_name='personrole',
            index=models.Index(fields=['effective_start', 'effective_end'], name='people_pers_effecti_543acb_idx'),
        ),
        migrations.AddIndex(
            model_name='personrole',
            index=models.Index(fields=['person', 'end_date'], name='people_pers_person__59076f_idx'),
        ),
        migrations.AddConstraint(
            model_name='personrole',
            constraint=models.UniqueConstraint(fields=('person', 'role', 'start_date'), name='uq_person_role_start'),
        ),
        migrations.AddConstraint(
            model_name='personrole',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date')), ('end_date__isnull', True), _connector='OR'), name='ck_assignment_dates'),
        ),
        migrations.AddConstraint(
            model_name='personrole',
            constraint=models.CheckConstraint(condition=models.Q(('effective_start__gte', models.F('start_date')), ('effective_start__isnull', True), _connector='OR'), name='ck_effective_after_start'),
        ),
        migrations.AddConstraint(
            model_name='personrole',
            constraint=models.CheckConstraint(condition=models.Q(('effective_end__gte', models.F('effective_start')), ('effective_end__isnull', True), ('effective_start__isnull', True), _connector='OR'), name='ck_effective_order'),
        ),
        migrations.AddConstraint(
            model_name='personrole',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_date__isnull', True), ('end_reason__isnull', True)), models.Q(('end_date__isnull', False), ('end_reason__isnull', False)), _connector='OR'), name='ck_end_reason_iff_end_date'),
        ),
        migrations.AddConstraint(
            model_name='personrole',
            constraint=models.CheckConstraint(condition=models.Q(('confirm_date__isnull', True), ('confirm_date__gte', models.F('start_date')), _connector='OR'), name='ck_confirm_after_start'),
        ),
    ]
