# Generated by Django 5.2.5 on 2025-11-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperson',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Record note'),
        ),
        migrations.AlterField(
            model_name='historicalpersonrole',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Record note'),
        ),
        migrations.AlterField(
            model_name='historicalrole',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Configuration note'),
        ),
        migrations.AlterField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Record note'),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Record note'),
        ),
        migrations.AlterField(
            model_name='role',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Configuration note'),
        ),
    ]
