# Generated by Django 5.2.5 on 2025-08-31 15:40

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_historicalperson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('ects_cap', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='ECTS cap')),
                ('is_elected', models.BooleanField(default=False, verbose_name='Elected position')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='historicalperson',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Person', 'verbose_name_plural': 'historical People'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archived at'),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Updated at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archived at'),
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='first_name',
            field=models.CharField(max_length=80, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='last_name',
            field=models.CharField(max_length=80, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=80, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=80, verbose_name='Last name'),
        ),
        migrations.CreateModel(
            name='HistoricalRole',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                ('ects_cap', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='ECTS cap')),
                ('is_elected', models.BooleanField(default=False, verbose_name='Elected position')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Role',
                'verbose_name_plural': 'historical Roles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPersonRole',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('additional_data', models.JSONField(blank=True, default=dict, verbose_name='Additional data')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.person', verbose_name='Person')),
                ('role', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.role', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'historical Person–Role assignment',
                'verbose_name_plural': 'historical Person–Role assignments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('additional_data', models.JSONField(blank=True, default=dict, verbose_name='Additional data')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='people.person', verbose_name='Person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='people.role', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Person–Role assignment',
                'verbose_name_plural': 'Person–Role assignments',
                'ordering': ['-start_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('person', 'role', 'start_date'), name='uq_person_role_start'), models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date')), ('end_date__isnull', True), _connector='OR'), name='ck_assignment_dates')],
            },
        ),
    ]
