# Generated by Django 5.2.5 on 2025-11-28 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_historicalperson_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrole',
            name='short_name',
            field=models.CharField(blank=True, help_text='Role short-form', max_length=30, validators=[django.core.validators.RegexValidator(message='Format: no digits, max. 30 characters, e.g. WiRef', regex='^\\D{1,30}$')], verbose_name='Short form'),
        ),
        migrations.AlterField(
            model_name='role',
            name='short_name',
            field=models.CharField(blank=True, help_text='Role short-form', max_length=30, validators=[django.core.validators.RegexValidator(message='Format: no digits, max. 30 characters, e.g. WiRef', regex='^\\D{1,30}$')], verbose_name='Short form'),
        ),
    ]
