# Generated by Django 5.2.5 on 2025-08-31 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_role_alter_historicalperson_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleTransitionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Reason',
                'verbose_name_plural': 'Reasons',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='historicalpersonrole',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Assignment', 'verbose_name_plural': 'historical Assignments'},
        ),
        migrations.AlterModelOptions(
            name='personrole',
            options={'ordering': ['-start_date', '-id'], 'verbose_name': 'Assignment', 'verbose_name_plural': 'Assignments'},
        ),
        migrations.RemoveField(
            model_name='historicalpersonrole',
            name='additional_data',
        ),
        migrations.RemoveField(
            model_name='historicalpersonrole',
            name='status',
        ),
        migrations.RemoveField(
            model_name='personrole',
            name='additional_data',
        ),
        migrations.RemoveField(
            model_name='personrole',
            name='status',
        ),
        migrations.AddField(
            model_name='historicalpersonrole',
            name='effective_end',
            field=models.DateField(blank=True, null=True, verbose_name='Effective end'),
        ),
        migrations.AddField(
            model_name='historicalpersonrole',
            name='effective_start',
            field=models.DateField(blank=True, null=True, verbose_name='Effective start'),
        ),
        migrations.AddField(
            model_name='historicalpersonrole',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='personrole',
            name='effective_end',
            field=models.DateField(blank=True, null=True, verbose_name='Effective end'),
        ),
        migrations.AddField(
            model_name='personrole',
            name='effective_start',
            field=models.DateField(blank=True, null=True, verbose_name='Effective start'),
        ),
        migrations.AddField(
            model_name='personrole',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='historicalpersonrole',
            name='reason',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.roletransitionreason', verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='personrole',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='people.roletransitionreason', verbose_name='Reason'),
        ),
        migrations.AddConstraint(
            model_name='personrole',
            constraint=models.CheckConstraint(condition=models.Q(('effective_start__gte', models.F('start_date')), ('effective_start__isnull', True), _connector='OR'), name='ck_effective_after_start'),
        ),
        migrations.AddConstraint(
            model_name='personrole',
            constraint=models.CheckConstraint(condition=models.Q(('effective_end__gte', models.F('effective_start')), ('effective_end__isnull', True), ('effective_start__isnull', True), _connector='OR'), name='ck_effective_order'),
        ),
    ]
