# Generated by Django 5.2.5 on 2025-09-04 15:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_roletransitionreason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('D', 'Diverse'), ('X', 'Not specified')], default='X', max_length=1, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='matric_no',
            field=models.CharField(blank=True, help_text='Example FH: s2210562023 — federal: 52103904', max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Use 's' + 10 digits (FH) or up to 10 digits (federal).", regex='^([sS]\\d{9,10}|\\d{1,10})$')], verbose_name='Matriculation number'),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Student email'),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Link to a Django user account (optional).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, help_text='Stable system identifier.', null=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('D', 'Diverse'), ('X', 'Not specified')], default='X', max_length=1, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='person',
            name='matric_no',
            field=models.CharField(blank=True, help_text='Example FH: s2210562023 — federal: 52103904', max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Use 's' + 10 digits (FH) or up to 10 digits (federal).", regex='^([sS]\\d{9,10}|\\d{1,10})$')], verbose_name='Matriculation number'),
        ),
        migrations.AddField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='person',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Student email'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link to a Django user account (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL, verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='person',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, help_text='Stable system identifier.', null=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='roletransitionreason',
            name='code',
            field=models.CharField(blank=True, help_text='Leave empty to auto-generate the next free code (R_00…R_99).', max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='Code must look like R_00 … R_99.', regex='^R_\\d{2}$')], verbose_name='Code'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['last_name', 'first_name'], name='people_pers_last_na_c63c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['matric_no'], name='people_pers_matric__87e6f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('matric_no__isnull', False)), fields=('matric_no',), name='uq_person_matric_no'),
        ),
    ]
