# Generated by Django 5.2.5 on 2025-09-04 15:57

from django.db import migrations
import uuid as _uuid

def gen_uuid(apps, schema_editor):
    Person = apps.get_model('people', 'Person')
    # Use .only('id','uuid') to keep it light
    for p in Person.objects.only('id', 'uuid').filter(uuid__isnull=True):
        p.uuid = _uuid.uuid4()
        p.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_historicalperson_gender_historicalperson_is_active_and_more'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, migrations.RunPython.noop),
    ]
