# Generated by Django 5.2.5 on 2025-09-04 16:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_fill_person_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperson',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Stable system identifier.', verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable system identifier.', unique=True, verbose_name='UUID'),
        ),
    ]
