# Generated by Django 5.2.5 on 2025-09-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_historicalpersonrole_end_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpersonrole',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='personrole',
            name='reason',
        ),
        migrations.AddConstraint(
            model_name='personrole',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_date__isnull', True), ('end_reason__isnull', True)), models.Q(('end_date__isnull', False), ('end_reason__isnull', False)), _connector='OR'), name='ck_end_reason_iff_end_date'),
        ),
        migrations.AddConstraint(
            model_name='personrole',
            constraint=models.CheckConstraint(condition=models.Q(('start_reason__isnull', True), ('end_reason__isnull', True), models.Q(('start_reason_id', models.F('end_reason_id')), _negated=True), _connector='OR'), name='ck_reasons_not_equal'),
        ),
    ]
