# Generated by Django 5.2.5 on 2025-09-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_remove_historicalpersonrole_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrole',
            name='is_stipend_reimbursed',
            field=models.BooleanField(default=False, help_text='Whether this role is ordinarily reimbursed via stipend [FuGeb]', verbose_name='Is reimbursed via stipend'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_stipend_reimbursed',
            field=models.BooleanField(default=False, help_text='Whether this role is ordinarily reimbursed via stipend [FuGeb]', verbose_name='Is reimbursed via stipend'),
        ),
    ]
