# Generated by Django 5.2.5 on 2025-09-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_historicalrole_is_stipend_reimbursed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrole',
            name='kind',
            field=models.CharField(choices=[('DEPT. HEAD', 'Department head (Referent:in)'), ('DEPT. CLERK', 'Department clerk (Sachbearbeiter:in)'), ('OTHER', 'Other / miscellaneous')], db_index=True, default='OTHER', help_text='Type of role within the (legal) personnel structure.', max_length=16, verbose_name='Role type'),
        ),
        migrations.AddField(
            model_name='role',
            name='kind',
            field=models.CharField(choices=[('DEPT. HEAD', 'Department head (Referent:in)'), ('DEPT. CLERK', 'Department clerk (Sachbearbeiter:in)'), ('OTHER', 'Other / miscellaneous')], db_index=True, default='OTHER', help_text='Type of role within the (legal) personnel structure.', max_length=16, verbose_name='Role type'),
        ),
        migrations.AlterField(
            model_name='historicalrole',
            name='ects_cap',
            field=models.DecimalField(decimal_places=1, default=0, help_text='The nominal reimbursible ECTS amount assigned to the role re: MOU with the academic board', max_digits=4, verbose_name='ECTS cap'),
        ),
        migrations.AlterField(
            model_name='historicalrole',
            name='is_elected',
            field=models.BooleanField(default=False, help_text='Whether this role is elected via an election authority re: HSG 2014', verbose_name='Elected position'),
        ),
        migrations.AlterField(
            model_name='historicalrole',
            name='is_stipend_reimbursed',
            field=models.BooleanField(default=False, help_text='Whether this role is ordinarily reimbursed via stipend [FuGeb]', verbose_name='Reimbursed via stipend'),
        ),
        migrations.AlterField(
            model_name='role',
            name='ects_cap',
            field=models.DecimalField(decimal_places=1, default=0, help_text='The nominal reimbursible ECTS amount assigned to the role re: MOU with the academic board', max_digits=4, verbose_name='ECTS cap'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_elected',
            field=models.BooleanField(default=False, help_text='Whether this role is elected via an election authority re: HSG 2014', verbose_name='Elected position'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_stipend_reimbursed',
            field=models.BooleanField(default=False, help_text='Whether this role is ordinarily reimbursed via stipend [FuGeb]', verbose_name='Reimbursed via stipend'),
        ),
    ]
