# Generated by Django 5.2.5 on 2025-09-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_historicalrole_kind_role_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonrole',
            name='confirm_date',
            field=models.DateField(blank=True, help_text='Date of assembly confirmation (if applicable)', null=True, verbose_name='Confirmation date'),
        ),
        migrations.AddField(
            model_name='historicalpersonrole',
            name='confirm_ref',
            field=models.CharField(blank=True, help_text='Assembly reference or note (if applicable)', max_length=120, null=True, verbose_name='Confirmation reference'),
        ),
        migrations.AddField(
            model_name='personrole',
            name='confirm_date',
            field=models.DateField(blank=True, help_text='Date of assembly confirmation (if applicable)', null=True, verbose_name='Confirmation date'),
        ),
        migrations.AddField(
            model_name='personrole',
            name='confirm_ref',
            field=models.CharField(blank=True, help_text='Assembly reference or note (if applicable)', max_length=120, null=True, verbose_name='Confirmation reference'),
        ),
        migrations.AddConstraint(
            model_name='personrole',
            constraint=models.CheckConstraint(condition=models.Q(('confirm_date__isnull', True), ('confirm_date__gte', models.F('start_date')), _connector='OR'), name='ck_confirm_after_start'),
        ),
    ]
