# Generated by Django 5.2.5 on 2025-09-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_historicalpersonrole_confirm_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrole',
            name='default_monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='default monthly pay (if eligible) per Statutes', max_digits=10, null=True, verbose_name='Default monthly stipend'),
        ),
        migrations.AddField(
            model_name='role',
            name='default_monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='default monthly pay (if eligible) per Statutes', max_digits=10, null=True, verbose_name='Default monthly stipend'),
        ),
    ]
