# Generated by Django 5.2.5 on 2025-09-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_historicalrole_default_monthly_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='personal_access_code',
            field=models.CharField(blank=True, db_index=True, help_text='To be shared with personnel for certain public filing systems (FuGeb etc.).', max_length=19, verbose_name='Personal access code'),
        ),
        migrations.AddField(
            model_name='person',
            name='personal_access_code',
            field=models.CharField(blank=True, help_text='To be shared with personnel for certain public filing systems (FuGeb etc.).', max_length=19, unique=True, verbose_name='Personal access code'),
        ),
    ]
