# Generated by Django 5.2.5 on 2025-09-30 03:48

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_historicalperson_personal_access_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpersonrole',
            name='confirm_ref',
            field=models.CharField(blank=True, help_text='Assembly reference or note (if applicable). Format: HV-<roman>-YYYY or AO-<roman>-YYYY (e.g. HV-IV-2024).', max_length=120, null=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='Use HV-<roman>-YYYY or AO-<roman>-YYYY (e.g. HV-IV-2024, AO-VI-2023).', regex='^(?:HV|AO)-[IVXLCDM]+-\\d{4}$')], verbose_name='Confirmation reference'),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='confirm_ref',
            field=models.CharField(blank=True, help_text='Assembly reference or note (if applicable). Format: HV-<roman>-YYYY or AO-<roman>-YYYY (e.g. HV-IV-2024).', max_length=120, null=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='Use HV-<roman>-YYYY or AO-<roman>-YYYY (e.g. HV-IV-2024, AO-VI-2023).', regex='^(?:HV|AO)-[IVXLCDM]+-\\d{4}$')], verbose_name='Confirmation reference'),
        ),
    ]
