# Generated by Django 5.2.5 on 2025-09-30 04:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_alter_historicalpersonrole_confirm_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrole',
            name='short_name',
            field=models.CharField(blank=True, help_text='Role short-form', max_length=20, validators=[django.core.validators.RegexValidator(message='Format: no digits, max. 20 characters, e.g. WiRef', regex='^\\D{1,20}$')], verbose_name='Short form'),
        ),
        migrations.AddField(
            model_name='role',
            name='short_name',
            field=models.CharField(blank=True, help_text='Role short-form', max_length=20, validators=[django.core.validators.RegexValidator(message='Format: no digits, max. 20 characters, e.g. WiRef', regex='^\\D{1,20}$')], verbose_name='Short form'),
        ),
    ]
