# Generated by Django 5.2.5 on 2025-10-27 22:19

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_historicalrole_short_name_role_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AddField(
            model_name='historicalpersonrole',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AddField(
            model_name='historicalrole',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AddField(
            model_name='person',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AddField(
            model_name='personrole',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AddField(
            model_name='role',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
    ]
