# Generated by Django 5.2.5 on 2025-10-29 19:15

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_historicalperson_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roletransitionreason',
            name='code',
            field=models.CharField(help_text='Stable code like I01, O01, C99.', max_length=4, unique=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='Use I## / O## / C## or X99 for Other.', regex='^(?:[IOC]\\d{2}|X99)$')], verbose_name='Code'),
        ),
    ]
