# Generated by Django 5.2.5 on 2025-10-29 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_alter_roletransitionreason_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='personrole',
            name='ck_reasons_not_equal',
        ),
    ]
