# Generated by Django 5.2.5 on 2025-10-29 19:47

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0019_remove_personrole_ck_reasons_not_equal'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletransitionreason',
            name='name_en',
            field=models.CharField(blank=True, help_text='Optional English label/name for the reason given.', max_length=120, verbose_name='Name (EN)'),
        ),
        migrations.AlterField(
            model_name='roletransitionreason',
            name='code',
            field=models.CharField(help_text="Stable code like I01, O01, C99 OR X99 (to be reserved for 'Other').", max_length=4, unique=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='Use I## / O## / C## or X99 for Other.', regex='^(?:[IOC]\\d{2}|X99)$')], verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='roletransitionreason',
            name='name',
            field=models.CharField(help_text='German label/name for the reason given (e.g. Eintritt, Austritt, ...).', max_length=120, verbose_name='Name'),
        ),
    ]
