# Generated by Django 5.2.5 on 2025-10-29 20:17

from django.db import migrations

def null_archived_at(apps, schema_editor):
    Person = apps.get_model("people", "Person")
    # Bulk update; no signals
    Person.objects.exclude(archived_at=None).update(archived_at=None)

class Migration(migrations.Migration):

    dependencies = [
        ('people', '0020_roletransitionreason_name_en_and_more'),
    ]

    operations = [
        migrations.RunPython(null_archived_at, migrations.RunPython.noop),
    ]
