# Generated by Django 5.2.5 on 2025-10-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0021_purge_archived_at_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalperson',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='archived_at',
        ),
    ]
