# Generated by Django 5.2.5 on 2025-10-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0022_remove_historicalperson_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrole',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Internal/admin role. Ignores stipend/ECTS expectations and is treated separately in policies.', verbose_name='System role'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Internal/admin role. Ignores stipend/ECTS expectations and is treated separately in policies.', verbose_name='System role'),
        ),
    ]
