# Generated by Django 5.2.5 on 2025-10-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0023_historicalrole_is_system_role_is_system'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='role',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_system', True), _negated=True), ('kind', 'OTHER'), _connector='OR'), name='ck_system_kind_other'),
        ),
    ]
