# Generated by Django 5.2.5 on 2025-11-02 08:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0024_role_system_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonrole',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpersonrole',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Updated at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
