# Generated by Django 5.2.5 on 2025-11-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0025_historicalpersonrole_created_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='personrole',
            index=models.Index(fields=['effective_start'], name='people_pers_effecti_7814bf_idx'),
        ),
        migrations.AddIndex(
            model_name='personrole',
            index=models.Index(fields=['effective_end'], name='people_pers_effecti_93522b_idx'),
        ),
        migrations.AddIndex(
            model_name='personrole',
            index=models.Index(fields=['effective_start', 'effective_end'], name='people_pers_effecti_543acb_idx'),
        ),
        migrations.AddIndex(
            model_name='personrole',
            index=models.Index(fields=['person', 'end_date'], name='people_pers_person__59076f_idx'),
        ),
    ]
