# Generated by Django 5.2.5 on 2025-11-09 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0001_initial'),
        ('people', '0026_personrole_people_pers_effecti_7814bf_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpersonrole',
            name='confirm_ref',
        ),
        migrations.RemoveField(
            model_name='personrole',
            name='confirm_ref',
        ),
        migrations.AddField(
            model_name='historicalpersonrole',
            name='elected_via',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Assembly session item that confirmed this appointment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assembly.sessionitem', verbose_name='Elected via'),
        ),
        migrations.AddField(
            model_name='personrole',
            name='elected_via',
            field=models.ForeignKey(blank=True, help_text='Assembly session item that confirmed this appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elected_persons', to='assembly.sessionitem', verbose_name='Elected via'),
        ),
    ]
