# Generated by Django 5.2.5 on 2025-10-18 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hankosign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='signatory',
            name='uq_signatory_user',
        ),
        migrations.RemoveField(
            model_name='historicalsignatory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='signatory',
            name='user',
        ),
    ]
