# Generated by Django 5.2.5 on 2025-12-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hankosign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsignature',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address from which signature was created (for audit/verification)', null=True, verbose_name='IP address'),
        ),
        migrations.AddField(
            model_name='signature',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address from which signature was created (for audit/verification)', null=True, verbose_name='IP address'),
        ),
    ]
