# Generated by Django 5.2.5 on 2025-10-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hankosign', '0002_remove_signatory_uq_signatory_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='verb',
            field=models.CharField(choices=[('SUBMIT', 'Submit'), ('VERIFY', 'Verify'), ('APPROVE', 'Approve'), ('RELEASE', 'Release/Print'), ('WITHDRAW', 'Withdraw'), ('REJECT', 'Reject')], max_length=20, verbose_name='Verb'),
        ),
        migrations.AlterField(
            model_name='historicalaction',
            name='verb',
            field=models.CharField(choices=[('SUBMIT', 'Submit'), ('VERIFY', 'Verify'), ('APPROVE', 'Approve'), ('RELEASE', 'Release/Print'), ('WITHDRAW', 'Withdraw'), ('REJECT', 'Reject')], max_length=20, verbose_name='Verb'),
        ),
    ]
