# Generated by Django 5.2.5 on 2025-10-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hankosign', '0003_alter_action_verb_alter_historicalaction_verb'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpolicy',
            name='is_repeatable',
            field=models.BooleanField(default=False, help_text='If enabled, the action linked to this policy can be performed multiple times on the same object.', verbose_name='Is repeatable'),
        ),
        migrations.AddField(
            model_name='policy',
            name='is_repeatable',
            field=models.BooleanField(default=False, help_text='If enabled, the action linked to this policy can be performed multiple times on the same object.', verbose_name='Is repeatable'),
        ),
    ]
