# Generated by Django 5.2.5 on 2025-10-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hankosign', '0004_historicalpolicy_is_repeatable_policy_is_repeatable'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsignature',
            name='is_repeatable',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='signature',
            name='is_repeatable',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
