# Generated by Django 5.2.5 on 2025-10-20 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hankosign', '0005_historicalsignature_is_repeatable_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='signature',
            unique_together=set(),
        ),
    ]
