# Generated by Django 5.2.5 on 2025-10-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hankosign', '0006_alter_signature_unique_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='signature',
            index=models.Index(fields=['content_type', 'object_id', 'verb', 'stage'], name='hankosign_s_content_d55459_idx'),
        ),
        migrations.AddConstraint(
            model_name='signature',
            constraint=models.UniqueConstraint(condition=models.Q(('is_repeatable', False)), fields=('content_type', 'object_id', 'verb', 'stage'), name='uq_sig_nonrepeat_per_object_verb_stage'),
        ),
    ]
