# Generated by Django 5.2.5 on 2025-10-31 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hankosign', '0008_alter_action_verb_alter_historicalaction_verb'),
        ('people', '0024_role_system_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='actions',
            field=models.ManyToManyField(blank=True, related_name='policies_m2m', to='hankosign.action', verbose_name='Additional actions'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='hankosign.action', verbose_name='Action'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['role'], name='hankosign_p_role_id_506f50_idx'),
        ),
    ]
