# Generated by Django 5.2.5 on 2025-10-31 17:54


from django.db import migrations

def copy_fk_to_m2m(apps, schema_editor):
    Policy = apps.get_model("hankosign", "Policy")
    # Using the historical model manager; it's safe to use .actions on it.
    for p in Policy.objects.exclude(action__isnull=True):
        # Add the FK’d action into the M2M set
        p.actions.add(p.action_id)

class Migration(migrations.Migration):

    dependencies = [
        ("hankosign", '0009_policy_m2m_schema'),  # replace XXXX with the previous migration name
    ]

    operations = [
        migrations.RunPython(copy_fk_to_m2m, migrations.RunPython.noop),
    ]


