# Generated by Django 5.2.5 on 2025-10-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hankosign', '0010_policy_backfill_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='is_repeatable',
            field=models.BooleanField(default=False, help_text='This action may be performed multiple times on the same object.', verbose_name='Repeatable'),
        ),
        migrations.AddField(
            model_name='action',
            name='require_distinct_signer',
            field=models.BooleanField(default=False, help_text='The same person cannot perform multiple gated stages on the same object.', verbose_name='Require distinct signer'),
        ),
        migrations.AddField(
            model_name='historicalaction',
            name='is_repeatable',
            field=models.BooleanField(default=False, help_text='This action may be performed multiple times on the same object.', verbose_name='Repeatable'),
        ),
        migrations.AddField(
            model_name='historicalaction',
            name='require_distinct_signer',
            field=models.BooleanField(default=False, help_text='The same person cannot perform multiple gated stages on the same object.', verbose_name='Require distinct signer'),
        ),
    ]
