# Generated by Django 5.2.5 on 2025-10-31 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hankosign', '0012_backfill_action_flags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpolicy',
            name='is_repeatable',
        ),
        migrations.RemoveField(
            model_name='historicalpolicy',
            name='require_distinct_signer',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='is_repeatable',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='require_distinct_signer',
        ),
    ]
