# Generated by Django 5.2.5 on 2025-11-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hankosign', '0013_remove_historicalpolicy_is_repeatable_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='signature',
            index=models.Index(fields=['at'], name='hankosign_s_at_b7181a_idx'),
        ),
        migrations.AddIndex(
            model_name='signature',
            index=models.Index(fields=['-at'], name='hankosign_s_at_4ad48c_idx'),
        ),
    ]
