# Generated by Django 5.2.5 on 2025-11-14 19:35

import concurrency.fields
import django.core.validators
import django.db.models.deletion
import finances.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("people", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Stored as WJyy_yy (e.g. WJ24_25). English UI shows FYyy_yy.",
                        max_length=12,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=80, verbose_name="Label"),
                ),
                (
                    "start",
                    models.DateField(
                        default=finances.models.default_start, verbose_name="Start date"
                    ),
                ),
                (
                    "end",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank to auto-fill (1 year − 1 day).",
                        null=True,
                        verbose_name="End date",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name": "Fiscal year",
                "verbose_name_plural": "Fiscal years",
                "ordering": ["-start"],
                "indexes": [
                    models.Index(fields=["start"], name="idx_fy_start"),
                    models.Index(fields=["code"], name="idx_fy_code"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end__gt", models.F("start"))),
                        name="ck_fy_dates_order",
                    ),
                    models.UniqueConstraint(fields=("start", "end"), name="uq_fy_span"),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="uq_fy_single_active_true",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalFiscalYear",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stored as WJyy_yy (e.g. WJ24_25). English UI shows FYyy_yy.",
                        max_length=12,
                        verbose_name="Code",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=80, verbose_name="Label"),
                ),
                (
                    "start",
                    models.DateField(
                        default=finances.models.default_start, verbose_name="Start date"
                    ),
                ),
                (
                    "end",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank to auto-fill (1 year − 1 day).",
                        null=True,
                        verbose_name="End date",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Updated at"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Fiscal year",
                "verbose_name_plural": "historical Fiscal years",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPaymentPlan",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "plan_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Auto-generated reference (e.g. WJ24_25-00001).",
                        max_length=24,
                        verbose_name="Plan code",
                    ),
                ),
                (
                    "cost_center",
                    models.CharField(
                        blank=True,
                        help_text="Cost center for the payment plan's personnel cost.",
                        max_length=3,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{3}$", "Enter a valid 3-digit cost center (KSt)"
                            )
                        ],
                        verbose_name="Cost center",
                    ),
                ),
                (
                    "payee_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Payee name"
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        blank=True,
                        help_text="Will only accept IBANs in correct format.",
                        max_length=34,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{2}\\d{2}[A-Z0-9]{10,30}$",
                                "Enter a valid IBAN (e.g. AT.., DE..).",
                            )
                        ],
                        verbose_name="IBAN",
                    ),
                ),
                (
                    "bic",
                    models.CharField(
                        blank=True,
                        help_text="Will only accept BIC/SWIFT in correct format.",
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$",
                                "Enter a valid BIC (8 or 11 chars).",
                            )
                        ],
                        verbose_name="BIC/SWIFT",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="For wire transfer.",
                        max_length=140,
                        verbose_name="Payment reference",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Format: Street, No., Post code, City.",
                        max_length=225,
                        verbose_name="Payee address",
                    ),
                ),
                (
                    "pay_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Pay start (optional)"
                    ),
                ),
                (
                    "pay_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Pay end (optional)"
                    ),
                ),
                (
                    "monthly_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly amount derived from assigned role. Can be edited.",
                        max_digits=10,
                        verbose_name="Monthly amount",
                    ),
                ),
                (
                    "total_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total amount derived from auto-calculation ['richtwert']. Can be edited.",
                        max_digits=10,
                        null=True,
                        verbose_name="Total amount (plan)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("FINISHED", "Finished"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        help_text="Status of payment plan. Payment plans can only be fully edited if they are in the DRAFT stage.",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "status_note",
                    models.CharField(
                        blank=True,
                        help_text="Short note describing the current status. Optional.",
                        max_length=200,
                        verbose_name="Status note (short)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Longer notes for internal use (e.g. 'Buchungsvermerke'). Optional.",
                        verbose_name="Notes (internal)",
                    ),
                ),
                (
                    "signed_person_at",
                    models.DateField(
                        blank=True,
                        help_text="Date of signature received.",
                        null=True,
                        verbose_name="Signed by payee on",
                    ),
                ),
                (
                    "pdf_file",
                    models.TextField(
                        blank=True,
                        help_text="Upload for the signed payment plan PDFs. Note: Simply re-upload after each signature.",
                        max_length=100,
                        null=True,
                        verbose_name="Signed PDF (optional)",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "version",
                    concurrency.fields.AutoIncVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finances.fiscalyear",
                        verbose_name="Fiscal year",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person_role",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="people.personrole",
                        verbose_name="Assignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Payment plan",
                "verbose_name_plural": "historical Payment plans",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="PaymentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_code",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated reference (e.g. WJ24_25-00001).",
                        max_length=24,
                        unique=True,
                        verbose_name="Plan code",
                    ),
                ),
                (
                    "cost_center",
                    models.CharField(
                        blank=True,
                        help_text="Cost center for the payment plan's personnel cost.",
                        max_length=3,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{3}$", "Enter a valid 3-digit cost center (KSt)"
                            )
                        ],
                        verbose_name="Cost center",
                    ),
                ),
                (
                    "payee_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Payee name"
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        blank=True,
                        help_text="Will only accept IBANs in correct format.",
                        max_length=34,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{2}\\d{2}[A-Z0-9]{10,30}$",
                                "Enter a valid IBAN (e.g. AT.., DE..).",
                            )
                        ],
                        verbose_name="IBAN",
                    ),
                ),
                (
                    "bic",
                    models.CharField(
                        blank=True,
                        help_text="Will only accept BIC/SWIFT in correct format.",
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$",
                                "Enter a valid BIC (8 or 11 chars).",
                            )
                        ],
                        verbose_name="BIC/SWIFT",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="For wire transfer.",
                        max_length=140,
                        verbose_name="Payment reference",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Format: Street, No., Post code, City.",
                        max_length=225,
                        verbose_name="Payee address",
                    ),
                ),
                (
                    "pay_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Pay start (optional)"
                    ),
                ),
                (
                    "pay_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Pay end (optional)"
                    ),
                ),
                (
                    "monthly_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly amount derived from assigned role. Can be edited.",
                        max_digits=10,
                        verbose_name="Monthly amount",
                    ),
                ),
                (
                    "total_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total amount derived from auto-calculation ['richtwert']. Can be edited.",
                        max_digits=10,
                        null=True,
                        verbose_name="Total amount (plan)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("FINISHED", "Finished"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        help_text="Status of payment plan. Payment plans can only be fully edited if they are in the DRAFT stage.",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "status_note",
                    models.CharField(
                        blank=True,
                        help_text="Short note describing the current status. Optional.",
                        max_length=200,
                        verbose_name="Status note (short)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Longer notes for internal use (e.g. 'Buchungsvermerke'). Optional.",
                        verbose_name="Notes (internal)",
                    ),
                ),
                (
                    "signed_person_at",
                    models.DateField(
                        blank=True,
                        help_text="Date of signature received.",
                        null=True,
                        verbose_name="Signed by payee on",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload for the signed payment plan PDFs. Note: Simply re-upload after each signature.",
                        null=True,
                        upload_to="payment_plans/%Y/%m/",
                        verbose_name="Signed PDF (optional)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    concurrency.fields.AutoIncVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_plans",
                        to="finances.fiscalyear",
                        verbose_name="Fiscal year",
                    ),
                ),
                (
                    "person_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_plans",
                        to="people.personrole",
                        verbose_name="Assignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment plan",
                "verbose_name_plural": "Payment plans",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["fiscal_year"], name="finances_pa_fiscal__9ee531_idx"
                    ),
                    models.Index(
                        fields=["person_role"], name="finances_pa_person__c964fa_idx"
                    ),
                    models.Index(
                        fields=["status"], name="finances_pa_status_5833d2_idx"
                    ),
                    models.Index(
                        fields=["plan_code"], name="finances_pa_plan_co_84f17f_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status__in", ["CANCELLED", "FINISHED"]), _negated=True
                        ),
                        fields=("person_role", "fiscal_year"),
                        name="uq_payment_plan_unique_per_pair_open",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "ACTIVE")),
                        fields=("person_role", "fiscal_year"),
                        name="uq_payment_plan_single_active_per_pair",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("pay_end__isnull", True),
                            ("pay_start__isnull", True),
                            ("pay_end__gte", models.F("pay_start")),
                            _connector="OR",
                        ),
                        name="ck_payment_plan_start_before_end",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("plan_code", ""), _negated=True),
                        name="ck_paymentplan_plan_code_nonempty",
                    ),
                ],
            },
        ),
    ]
