# Generated by Django 5.2.5 on 2025-09-08 23:10

import django.db.models.deletion
import finances.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Stored as WJyy_yy (e.g. WJ24_25). English UI shows FYyy_yy.', max_length=12, unique=True, verbose_name='Code')),
                ('label', models.CharField(blank=True, max_length=80, verbose_name='Label')),
                ('start', models.DateField(default=finances.models.default_start, verbose_name='Start date')),
                ('end', models.DateField(blank=True, help_text='Leave blank to auto-fill (1 year − 1 day).', null=True, verbose_name='End date')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Fiscal year',
                'verbose_name_plural': 'Fiscal years',
                'ordering': ['-start'],
                'indexes': [models.Index(fields=['start'], name='idx_fy_start'), models.Index(fields=['code'], name='idx_fy_code')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='ck_fy_dates_order'), models.UniqueConstraint(fields=('start', 'end'), name='uq_fy_span')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalFiscalYear',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, help_text='Stored as WJyy_yy (e.g. WJ24_25). English UI shows FYyy_yy.', max_length=12, verbose_name='Code')),
                ('label', models.CharField(blank=True, max_length=80, verbose_name='Label')),
                ('start', models.DateField(default=finances.models.default_start, verbose_name='Start date')),
                ('end', models.DateField(blank=True, help_text='Leave blank to auto-fill (1 year − 1 day).', null=True, verbose_name='End date')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Fiscal year',
                'verbose_name_plural': 'historical Fiscal years',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
