# Generated by Django 5.2.5 on 2025-11-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpaymentplan",
            name="submission_ip",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP address from which the public portal form was submitted.",
                null=True,
                verbose_name="Submission IP",
            ),
        ),
        migrations.AddField(
            model_name="paymentplan",
            name="submission_ip",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP address from which the public portal form was submitted.",
                null=True,
                verbose_name="Submission IP",
            ),
        ),
    ]
