# Generated by Django 5.2.5 on 2025-09-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyear',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked years are read-only.', verbose_name='Locked'),
        ),
        migrations.AddField(
            model_name='historicalfiscalyear',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked years are read-only.', verbose_name='Locked'),
        ),
    ]
