# Generated by Django 5.2.5 on 2025-11-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_historicalpaymentplan_submission_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaymentplan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('FINISHED', 'Finished')], default='DRAFT', help_text='Status of payment plan. Payment plans can only be fully edited if they are in the DRAFT stage.', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('FINISHED', 'Finished')], default='DRAFT', help_text='Status of payment plan. Payment plans can only be fully edited if they are in the DRAFT stage.', max_length=10, verbose_name='Status'),
        ),
    ]
