# Generated by Django 5.2.5 on 2025-09-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_fiscalyear_is_locked_historicalfiscalyear_is_locked'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fiscalyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='uq_fy_single_active_true'),
        ),
    ]
