# Generated by Django 5.2.5 on 2025-09-14 22:10

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_fiscalyear_uq_fy_single_active_true'),
        ('people', '0013_historicalrole_default_monthly_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPaymentPlan',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('payee_name', models.CharField(blank=True, max_length=200, verbose_name='Payee name (optional override)')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, verbose_name='BIC')),
                ('reference', models.CharField(blank=True, max_length=140, verbose_name='Payment reference')),
                ('pay_start', models.DateField(blank=True, null=True, verbose_name='Pay start (optional)')),
                ('pay_end', models.DateField(blank=True, null=True, verbose_name='Pay end (optional)')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monthly amount')),
                ('total_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total override (optional)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10, verbose_name='Status')),
                ('status_note', models.CharField(blank=True, max_length=200, verbose_name='Status note (short)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes (internal)')),
                ('signed_person_at', models.DateField(blank=True, null=True, verbose_name='Signed by payee on')),
                ('signed_wiref_at', models.DateField(blank=True, null=True, verbose_name='Signed by WiRef on')),
                ('signed_chair_at', models.DateField(blank=True, null=True, verbose_name='Signed by chair on')),
                ('pdf_file', models.TextField(blank=True, max_length=100, null=True, verbose_name='Signed PDF (optional)')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fiscal_year', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finances.fiscalyear', verbose_name='Fiscal year')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person_role', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.personrole', verbose_name='Assignment')),
            ],
            options={
                'verbose_name': 'historical Payment plan',
                'verbose_name_plural': 'historical Payment plans',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee_name', models.CharField(blank=True, max_length=200, verbose_name='Payee name (optional override)')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, verbose_name='BIC')),
                ('reference', models.CharField(blank=True, max_length=140, verbose_name='Payment reference')),
                ('pay_start', models.DateField(blank=True, null=True, verbose_name='Pay start (optional)')),
                ('pay_end', models.DateField(blank=True, null=True, verbose_name='Pay end (optional)')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monthly amount')),
                ('total_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total override (optional)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10, verbose_name='Status')),
                ('status_note', models.CharField(blank=True, max_length=200, verbose_name='Status note (short)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes (internal)')),
                ('signed_person_at', models.DateField(blank=True, null=True, verbose_name='Signed by payee on')),
                ('signed_wiref_at', models.DateField(blank=True, null=True, verbose_name='Signed by WiRef on')),
                ('signed_chair_at', models.DateField(blank=True, null=True, verbose_name='Signed by chair on')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='payment_plans/%Y/%m/', verbose_name='Signed PDF (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_plans', to='finances.fiscalyear', verbose_name='Fiscal year')),
                ('person_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_plans', to='people.personrole', verbose_name='Assignment')),
            ],
            options={
                'verbose_name': 'Payment plan',
                'verbose_name_plural': 'Payment plans',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['fiscal_year'], name='finances_pa_fiscal__9ee531_idx'), models.Index(fields=['person_role'], name='finances_pa_person__c964fa_idx'), models.Index(fields=['status'], name='finances_pa_status_5833d2_idx')],
                'constraints': [models.UniqueConstraint(fields=('person_role', 'fiscal_year'), name='uq_payment_plan_unique_per_assignment_fy'), models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('person_role', 'fiscal_year'), name='uq_payment_plan_single_active_per_pair'), models.CheckConstraint(condition=models.Q(('pay_end__isnull', True), ('pay_start__isnull', True), ('pay_end__gte', models.F('pay_start')), _connector='OR'), name='ck_payment_plan_start_before_end')],
            },
        ),
    ]
