# Generated by Django 5.2.5 on 2025-11-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_historicalpaymentplan_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpaymentplan',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='historicalpaymentplan',
            name='status_note',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='status_note',
        ),
    ]
