# Generated by Django 5.2.5 on 2025-11-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_remove_historicalpaymentplan_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaymentplan',
            name='monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly amount derived from assigned role. Can be edited.', max_digits=10, null=True, verbose_name='Monthly amount'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly amount derived from assigned role. Can be edited.', max_digits=10, null=True, verbose_name='Monthly amount'),
        ),
    ]
