# Generated by Django 5.2.5 on 2025-09-20 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_historicalpaymentplan_paymentplan'),
        ('people', '0013_historicalrole_default_monthly_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymentplan',
            name='plan_code',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated reference (e.g. WJ24_25-00001).', max_length=24, verbose_name='Plan code'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='plan_code',
            field=models.CharField(blank=True, help_text='Auto-generated reference (e.g. WJ24_25-00001).', max_length=24, unique=True, verbose_name='Plan code'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentplan',
            name='bic',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$', 'Enter a valid BIC (8 or 11 chars).')], verbose_name='BIC'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentplan',
            name='iban',
            field=models.CharField(blank=True, max_length=34, validators=[django.core.validators.RegexValidator('^[A-Z]{2}\\d{2}[A-Z0-9]{10,30}$', 'Enter a valid IBAN (e.g. AT.., DE..).')], verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='bic',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$', 'Enter a valid BIC (8 or 11 chars).')], verbose_name='BIC'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='iban',
            field=models.CharField(blank=True, max_length=34, validators=[django.core.validators.RegexValidator('^[A-Z]{2}\\d{2}[A-Z0-9]{10,30}$', 'Enter a valid IBAN (e.g. AT.., DE..).')], verbose_name='IBAN'),
        ),
        migrations.AddIndex(
            model_name='paymentplan',
            index=models.Index(fields=['plan_code'], name='finances_pa_plan_co_84f17f_idx'),
        ),
    ]
