# Generated by Django 5.2.5 on 2025-11-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_alter_historicalpaymentplan_monthly_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaymentplan',
            name='total_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Total amount derived from auto-calculation ['richtwert']. Can be edited.", max_digits=10, null=True, verbose_name='Total amount (override)'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='total_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Total amount derived from auto-calculation ['richtwert']. Can be edited.", max_digits=10, null=True, verbose_name='Total amount (override)'),
        ),
    ]
