# Generated by Django 5.2.5 on 2025-12-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_alter_historicalpaymentplan_total_override_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active (SSP Filing)'),
        ),
        migrations.AlterField(
            model_name='historicalfiscalyear',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active (SSP Filing)'),
        ),
    ]
