# Generated by Django 5.2.5 on 2025-09-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_backfill_plan_codes_fix_empty'),
        ('people', '0013_historicalrole_default_monthly_amount_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentplan',
            constraint=models.CheckConstraint(condition=models.Q(('plan_code', ''), _negated=True), name='ck_paymentplan_plan_code_nonempty'),
        ),
    ]
