# Generated by Django 5.2.5 on 2025-09-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_ensure_nonempty_plan_code'),
        ('people', '0013_historicalrole_default_monthly_amount_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), fields=('person_role', 'fiscal_year'), name='uq_payment_plan_unique_per_pair_non_cancelled'),
        ),
    ]
