# Generated by Django 5.2.5 on 2025-09-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_relax_unique_for_cancelled'),
        ('people', '0013_historicalrole_default_monthly_amount_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentplan',
            name='uq_payment_plan_unique_per_assignment_fy',
        ),
        migrations.RemoveConstraint(
            model_name='paymentplan',
            name='uq_payment_plan_unique_per_pair_non_cancelled',
        ),
        migrations.AddConstraint(
            model_name='paymentplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['CANCELLED', 'FINISHED']), _negated=True), fields=('person_role', 'fiscal_year'), name='uq_payment_plan_unique_per_pair_open'),
        ),
    ]
