# Generated by Django 5.2.5 on 2025-09-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_unify_unique_constraint_open_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymentplan',
            name='address',
            field=models.CharField(blank=True, help_text='Street, No., Post code, City', max_length=225, verbose_name='Payee address'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='address',
            field=models.CharField(blank=True, help_text='Street, No., Post code, City', max_length=225, verbose_name='Payee address'),
        ),
    ]
