# Generated by Django 5.2.5 on 2025-09-25 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_historicalpaymentplan_address_paymentplan_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymentplan',
            name='cost_center',
            field=models.CharField(blank=True, help_text="Cost center for the payment plan's personnel cost.", max_length=3, null=True, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'Enter a valid 3-digit cost center (KSt)')], verbose_name='Cost center'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='cost_center',
            field=models.CharField(blank=True, help_text="Cost center for the payment plan's personnel cost.", max_length=3, null=True, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'Enter a valid 3-digit cost center (KSt)')], verbose_name='Cost center'),
        ),
    ]
