# Generated by Django 5.2.5 on 2025-11-01 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_historicalpaymentplan_cost_center_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaymentplan',
            name='address',
            field=models.CharField(blank=True, help_text='Format: Street, No., Post code, City.', max_length=225, verbose_name='Payee address'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentplan',
            name='bic',
            field=models.CharField(blank=True, help_text='Will only accept BIC/SWIFT in correct format.', max_length=11, validators=[django.core.validators.RegexValidator('^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$', 'Enter a valid BIC (8 or 11 chars).')], verbose_name='BIC/SWIFT'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentplan',
            name='iban',
            field=models.CharField(blank=True, help_text='Will only accept IBANs in correct format.', max_length=34, validators=[django.core.validators.RegexValidator('^[A-Z]{2}\\d{2}[A-Z0-9]{10,30}$', 'Enter a valid IBAN (e.g. AT.., DE..).')], verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentplan',
            name='monthly_amount',
            field=models.DecimalField(decimal_places=2, help_text='Monthly amount derived from assigned role. Can be edited.', max_digits=10, verbose_name='Monthly amount'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentplan',
            name='notes',
            field=models.TextField(blank=True, help_text="Longer notes for internal use (e.g. 'Buchungsvermerke'). Optional.", verbose_name='Notes (internal)'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentplan',
            name='payee_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Payee name'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentplan',
            name='pdf_file',
            field=models.TextField(blank=True, help_text='Upload for the signed payment plan PDFs. Note: Simply re-upload after each signature.', max_length=100, null=True, verbose_name='Signed PDF (optional)'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentplan',
            name='reference',
            field=models.CharField(blank=True, help_text='For wire transfer.', max_length=140, verbose_name='Payment reference'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentplan',
            name='signed_chair_at',
            field=models.DateField(blank=True, help_text='Date of signature received.', null=True, verbose_name='Signed by chair on'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentplan',
            name='signed_person_at',
            field=models.DateField(blank=True, help_text='Date of signature received.', null=True, verbose_name='Signed by payee on'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentplan',
            name='signed_wiref_at',
            field=models.DateField(blank=True, help_text='Date of signature received.', null=True, verbose_name='Signed by WiRef on'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentplan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Status of payment plan. Payment plans can only be fully edited if they are in the DRAFT stage.', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentplan',
            name='status_note',
            field=models.CharField(blank=True, help_text='Short note describing the current status. Optional.', max_length=200, verbose_name='Status note (short)'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentplan',
            name='total_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Total amount derived from auto-calculation ['richtwert']. Can be edited.", max_digits=10, null=True, verbose_name='Total amount (plan)'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='address',
            field=models.CharField(blank=True, help_text='Format: Street, No., Post code, City.', max_length=225, verbose_name='Payee address'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='bic',
            field=models.CharField(blank=True, help_text='Will only accept BIC/SWIFT in correct format.', max_length=11, validators=[django.core.validators.RegexValidator('^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$', 'Enter a valid BIC (8 or 11 chars).')], verbose_name='BIC/SWIFT'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='iban',
            field=models.CharField(blank=True, help_text='Will only accept IBANs in correct format.', max_length=34, validators=[django.core.validators.RegexValidator('^[A-Z]{2}\\d{2}[A-Z0-9]{10,30}$', 'Enter a valid IBAN (e.g. AT.., DE..).')], verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='monthly_amount',
            field=models.DecimalField(decimal_places=2, help_text='Monthly amount derived from assigned role. Can be edited.', max_digits=10, verbose_name='Monthly amount'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='notes',
            field=models.TextField(blank=True, help_text="Longer notes for internal use (e.g. 'Buchungsvermerke'). Optional.", verbose_name='Notes (internal)'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='payee_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Payee name'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload for the signed payment plan PDFs. Note: Simply re-upload after each signature.', null=True, upload_to='payment_plans/%Y/%m/', verbose_name='Signed PDF (optional)'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='reference',
            field=models.CharField(blank=True, help_text='For wire transfer.', max_length=140, verbose_name='Payment reference'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='signed_chair_at',
            field=models.DateField(blank=True, help_text='Date of signature received.', null=True, verbose_name='Signed by chair on'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='signed_person_at',
            field=models.DateField(blank=True, help_text='Date of signature received.', null=True, verbose_name='Signed by payee on'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='signed_wiref_at',
            field=models.DateField(blank=True, help_text='Date of signature received.', null=True, verbose_name='Signed by WiRef on'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Status of payment plan. Payment plans can only be fully edited if they are in the DRAFT stage.', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='status_note',
            field=models.CharField(blank=True, help_text='Short note describing the current status. Optional.', max_length=200, verbose_name='Status note (short)'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='total_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Total amount derived from auto-calculation ['richtwert']. Can be edited.", max_digits=10, null=True, verbose_name='Total amount (plan)'),
        ),
    ]
