# Generated by Django 5.2.5 on 2025-11-01 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0013_alter_historicalpaymentplan_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpaymentplan',
            name='signed_chair_at',
        ),
        migrations.RemoveField(
            model_name='historicalpaymentplan',
            name='signed_wiref_at',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='signed_chair_at',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='signed_wiref_at',
        ),
    ]
