# Generated by Django 5.2.5 on 2025-11-01 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0014_remove_historicalpaymentplan_signed_chair_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiscalyear',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='historicalfiscalyear',
            name='is_locked',
        ),
    ]
