# Generated by Django 5.2.5 on 2025-11-02 21:59

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0015_remove_fiscalyear_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymentplan',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
    ]
