# Generated by Django 5.2.5 on 2025-11-14 19:35

import concurrency.fields
import django.db.models.deletion
import simple_history.models
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Composition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
            ],
            options={
                "verbose_name": "Composition",
                "verbose_name_plural": "Compositions",
            },
        ),
        migrations.CreateModel(
            name="HistoricalMandate",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        help_text="Seat number (1-9)", verbose_name="Position"
                    ),
                ),
                (
                    "officer_role",
                    models.CharField(
                        choices=[
                            ("CHAIR", "Vorsitzende/r"),
                            ("DEP1", "1. Stellvertretung"),
                            ("DEP2", "2. Stellvertretung"),
                            ("MEMB", "Mandatar/in"),
                        ],
                        default="MEMB",
                        max_length=5,
                        verbose_name="Officer role",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End date"),
                ),
                (
                    "backup_person_text",
                    models.CharField(
                        blank=True,
                        help_text="For externals not in the system",
                        max_length=200,
                        verbose_name="Backup person (external)",
                    ),
                ),
                (
                    "party",
                    models.CharField(
                        blank=True,
                        help_text="Wahlwerbende Gruppe/Liste (e.g., VSSTÖ, AG, GRAS)",
                        max_length=100,
                        verbose_name="Party affiliation",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Updated at"
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Mandate",
                "verbose_name_plural": "historical Mandates",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSession",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Auto-generated: HV25_27_I:or",
                        max_length=30,
                        verbose_name="Code",
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[("or", "Ordentlich"), ("ao", "Außerordentlich")],
                        default="or",
                        max_length=2,
                        verbose_name="Session type",
                    ),
                ),
                ("session_date", models.DateField(verbose_name="Session date")),
                (
                    "session_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Session time"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Location"
                    ),
                ),
                (
                    "protocol_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Protocol number"
                    ),
                ),
                (
                    "other_attendees",
                    models.TextField(
                        blank=True,
                        help_text="External guests (Anna Bauer; Peter Müller; ...)",
                        verbose_name="Other attendees",
                    ),
                ),
                (
                    "invitations_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Invitations sent at"
                    ),
                ),
                (
                    "minutes_finalized_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Minutes finalized at"
                    ),
                ),
                (
                    "sent_koko_hsg_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sent to KoKo/HSG at"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Updated at"
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Session",
                "verbose_name_plural": "historical Sessions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSessionItem",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "item_code",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated: S001, S002, ...",
                        max_length=10,
                        verbose_name="Item code",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        help_text="Position in agenda", verbose_name="Order"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("RES", "Beschluss"),
                            ("PROC", "Ablaufinformation"),
                            ("ELEC", "Beschluss iSe Personalwahl"),
                        ],
                        max_length=10,
                        verbose_name="Kind",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Title")),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="For procedural items",
                        verbose_name="Content",
                    ),
                ),
                (
                    "subject",
                    tinymce.models.HTMLField(
                        blank=True,
                        help_text="Subject of the item",
                        verbose_name="Subject",
                    ),
                ),
                (
                    "discussion",
                    tinymce.models.HTMLField(
                        blank=True,
                        help_text="Discussion contents for the item",
                        verbose_name="Discussion",
                    ),
                ),
                (
                    "outcome",
                    tinymce.models.HTMLField(
                        blank=True,
                        help_text="Result or outcome for the item",
                        verbose_name="Outcome",
                    ),
                ),
                (
                    "voting_mode",
                    models.CharField(
                        choices=[
                            ("NONE", "Keine Abstimmung"),
                            ("COUNT", "Stimmenzählung"),
                            ("NAMED", "Namentliche Abstimmung"),
                        ],
                        default="NONE",
                        max_length=10,
                        verbose_name="Voting mode",
                    ),
                ),
                (
                    "votes_for",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Votes for"
                    ),
                ),
                (
                    "votes_against",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Votes against"
                    ),
                ),
                (
                    "votes_abstain",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Abstentions"
                    ),
                ),
                (
                    "passed",
                    models.BooleanField(blank=True, null=True, verbose_name="Passed"),
                ),
                (
                    "elected_person_text_reference",
                    models.CharField(
                        blank=True,
                        help_text="Temporary text reference for elected person - to be linked to PersonRole later",
                        max_length=200,
                        verbose_name="Elected person (text reference)",
                    ),
                ),
                (
                    "elected_role_text_reference",
                    models.CharField(
                        blank=True,
                        help_text="Temporary text reference for elected role - to be linked to PersonRole later",
                        max_length=200,
                        verbose_name="Elected role (text reference)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Updated at"
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Session Item",
                "verbose_name_plural": "historical Session Items",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTerm",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Auto-generated: HV25_27",
                        max_length=20,
                        verbose_name="Code",
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="Label")),
                ("start_date", models.DateField(verbose_name="Start date")),
                (
                    "end_date",
                    models.DateField(
                        help_text="Usually +2 years from start", verbose_name="End date"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one term can be active at a time",
                        verbose_name="Active term",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Updated at"
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Term",
                "verbose_name_plural": "historical Terms",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Mandate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        help_text="Seat number (1-9)", verbose_name="Position"
                    ),
                ),
                (
                    "officer_role",
                    models.CharField(
                        choices=[
                            ("CHAIR", "Vorsitzende/r"),
                            ("DEP1", "1. Stellvertretung"),
                            ("DEP2", "2. Stellvertretung"),
                            ("MEMB", "Mandatar/in"),
                        ],
                        default="MEMB",
                        max_length=5,
                        verbose_name="Officer role",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End date"),
                ),
                (
                    "backup_person_text",
                    models.CharField(
                        blank=True,
                        help_text="For externals not in the system",
                        max_length=200,
                        verbose_name="Backup person (external)",
                    ),
                ),
                (
                    "party",
                    models.CharField(
                        blank=True,
                        help_text="Wahlwerbende Gruppe/Liste (e.g., VSSTÖ, AG, GRAS)",
                        max_length=100,
                        verbose_name="Party affiliation",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mandate",
                "verbose_name_plural": "Mandates",
                "ordering": ["position", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated: HV25_27_I:or",
                        max_length=30,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[("or", "Ordentlich"), ("ao", "Außerordentlich")],
                        default="or",
                        max_length=2,
                        verbose_name="Session type",
                    ),
                ),
                ("session_date", models.DateField(verbose_name="Session date")),
                (
                    "session_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Session time"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Location"
                    ),
                ),
                (
                    "protocol_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Protocol number"
                    ),
                ),
                (
                    "other_attendees",
                    models.TextField(
                        blank=True,
                        help_text="External guests (Anna Bauer; Peter Müller; ...)",
                        verbose_name="Other attendees",
                    ),
                ),
                (
                    "invitations_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Invitations sent at"
                    ),
                ),
                (
                    "minutes_finalized_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Minutes finalized at"
                    ),
                ),
                (
                    "sent_koko_hsg_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sent to KoKo/HSG at"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
            ],
            options={
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
                "ordering": ["-session_date", "code"],
            },
        ),
        migrations.CreateModel(
            name="SessionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_code",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated: S001, S002, ...",
                        max_length=10,
                        verbose_name="Item code",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        help_text="Position in agenda", verbose_name="Order"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("RES", "Beschluss"),
                            ("PROC", "Ablaufinformation"),
                            ("ELEC", "Beschluss iSe Personalwahl"),
                        ],
                        max_length=10,
                        verbose_name="Kind",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Title")),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="For procedural items",
                        verbose_name="Content",
                    ),
                ),
                (
                    "subject",
                    tinymce.models.HTMLField(
                        blank=True,
                        help_text="Subject of the item",
                        verbose_name="Subject",
                    ),
                ),
                (
                    "discussion",
                    tinymce.models.HTMLField(
                        blank=True,
                        help_text="Discussion contents for the item",
                        verbose_name="Discussion",
                    ),
                ),
                (
                    "outcome",
                    tinymce.models.HTMLField(
                        blank=True,
                        help_text="Result or outcome for the item",
                        verbose_name="Outcome",
                    ),
                ),
                (
                    "voting_mode",
                    models.CharField(
                        choices=[
                            ("NONE", "Keine Abstimmung"),
                            ("COUNT", "Stimmenzählung"),
                            ("NAMED", "Namentliche Abstimmung"),
                        ],
                        default="NONE",
                        max_length=10,
                        verbose_name="Voting mode",
                    ),
                ),
                (
                    "votes_for",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Votes for"
                    ),
                ),
                (
                    "votes_against",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Votes against"
                    ),
                ),
                (
                    "votes_abstain",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Abstentions"
                    ),
                ),
                (
                    "passed",
                    models.BooleanField(blank=True, null=True, verbose_name="Passed"),
                ),
                (
                    "elected_person_text_reference",
                    models.CharField(
                        blank=True,
                        help_text="Temporary text reference for elected person - to be linked to PersonRole later",
                        max_length=200,
                        verbose_name="Elected person (text reference)",
                    ),
                ),
                (
                    "elected_role_text_reference",
                    models.CharField(
                        blank=True,
                        help_text="Temporary text reference for elected role - to be linked to PersonRole later",
                        max_length=200,
                        verbose_name="Elected role (text reference)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
            ],
            options={
                "verbose_name": "Session Item",
                "verbose_name_plural": "Session Items",
                "ordering": ["session", "order"],
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated: HV25_27",
                        max_length=20,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="Label")),
                ("start_date", models.DateField(verbose_name="Start date")),
                (
                    "end_date",
                    models.DateField(
                        help_text="Usually +2 years from start", verbose_name="End date"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one term can be active at a time",
                        verbose_name="Active term",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
            ],
            options={
                "verbose_name": "Term",
                "verbose_name_plural": "Terms",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[
                            ("FOR", "Ja"),
                            ("AGAINST", "Nein"),
                            ("ABSTAIN", "Enthaltung"),
                        ],
                        max_length=10,
                        verbose_name="Vote",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name": "Vote",
                "verbose_name_plural": "Votes",
            },
        ),
        migrations.CreateModel(
            name="HistoricalComposition",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Updated at"
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Composition",
                "verbose_name_plural": "historical Compositions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
