# Generated by Django 5.2.5 on 2025-11-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmandate',
            name='party',
            field=models.CharField(blank=True, help_text='Wahlwerbende Gruppe/Liste (e.g., VSSTÖ, AG, GRAS)', max_length=100, verbose_name='Party affiliation'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='party',
            field=models.CharField(blank=True, help_text='Wahlwerbende Gruppe/Liste (e.g., VSSTÖ, AG, GRAS)', max_length=100, verbose_name='Party affiliation'),
        ),
    ]
