# Generated by Django 5.2.5 on 2025-11-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0002_historicalmandate_party_mandate_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsessionitem',
            name='elected_person_text_reference',
            field=models.CharField(blank=True, help_text='Temporary text reference for elected person - to be linked to PersonRole later', max_length=200, verbose_name='Elected person (text reference)'),
        ),
        migrations.AddField(
            model_name='sessionitem',
            name='elected_person_text_reference',
            field=models.CharField(blank=True, help_text='Temporary text reference for elected person - to be linked to PersonRole later', max_length=200, verbose_name='Elected person (text reference)'),
        ),
        migrations.AlterField(
            model_name='historicalsessionitem',
            name='kind',
            field=models.CharField(choices=[('RES', 'Beschluss'), ('PROC', 'Ablaufinformation'), ('ELEC', 'Beschluss iSe Personalwahl')], max_length=10, verbose_name='Kind'),
        ),
        migrations.AlterField(
            model_name='sessionitem',
            name='kind',
            field=models.CharField(choices=[('RES', 'Beschluss'), ('PROC', 'Ablaufinformation'), ('ELEC', 'Beschluss iSe Personalwahl')], max_length=10, verbose_name='Kind'),
        ),
    ]
