# Generated by Django 5.2.5 on 2025-11-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='historicalcomposition',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='historicalsession',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='historicalterm',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='session',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='term',
            name='notes',
        ),
        migrations.AddField(
            model_name='historicalsession',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved by Chair'), ('VERIFIED', 'Sent to KoKo/HSG'), ('REJECTED', 'Rejected re-work')], db_index=True, default='DRAFT', help_text='Workflow status derived from signatures.', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved by Chair'), ('VERIFIED', 'Sent to KoKo/HSG'), ('REJECTED', 'Rejected re-work')], db_index=True, default='DRAFT', help_text='Workflow status derived from signatures.', max_length=20, verbose_name='Status'),
        ),
    ]
