# Generated by Django 5.2.5 on 2025-11-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0003_historicalsessionitem_elected_person_text_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsessionitem',
            name='elected_role_text_reference',
            field=models.CharField(blank=True, help_text='Temporary text reference for elected role - to be linked to PersonRole later', max_length=200, verbose_name='Elected role (text reference)'),
        ),
        migrations.AddField(
            model_name='sessionitem',
            name='elected_role_text_reference',
            field=models.CharField(blank=True, help_text='Temporary text reference for elected role - to be linked to PersonRole later', max_length=200, verbose_name='Elected role (text reference)'),
        ),
    ]
