# Generated by Django 5.2.5 on 2025-11-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0004_add_attendance_tracking'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sessionattendance',
            name='assembly_sessionattendance_unique_session_mandate',
        ),
        migrations.AlterUniqueTogether(
            name='sessionattendance',
            unique_together={('session', 'mandate')},
        ),
    ]
