# Generated by Django 5.2.5 on 2025-11-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0005_remove_sessionattendance_assembly_sessionattendance_unique_session_mandate_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessionattendance',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='sessionattendance',
            constraint=models.UniqueConstraint(fields=('session', 'mandate'), name='uq_attendance_session_mandate'),
        ),
    ]
