# Generated by Django 5.2.5 on 2025-12-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0006_alter_sessionattendance_unique_together_and_more'),
        ('people', '0004_person_uq_person_email'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mandate',
            index=models.Index(fields=['composition', 'position'], name='assembly_ma_composi_d440c1_idx'),
        ),
        migrations.AddIndex(
            model_name='mandate',
            index=models.Index(fields=['officer_role'], name='assembly_ma_officer_4f54ce_idx'),
        ),
        migrations.AddIndex(
            model_name='mandate',
            index=models.Index(fields=['start_date', 'end_date'], name='assembly_ma_start_d_e7df14_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['term', 'session_date'], name='assembly_se_term_id_3e53b5_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['session_type'], name='assembly_se_session_53e7a4_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['-session_date'], name='assembly_se_session_c3308b_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionitem',
            index=models.Index(fields=['session', 'order'], name='assembly_se_session_d03cc0_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionitem',
            index=models.Index(fields=['kind'], name='assembly_se_kind_ccb81f_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionitem',
            index=models.Index(fields=['voting_mode'], name='assembly_se_voting__531eda_idx'),
        ),
    ]
