# Generated by Django 5.2.5 on 2025-12-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0007_mandate_assembly_ma_composi_d440c1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmandate',
            name='officer_role',
            field=models.CharField(choices=[('CHAIR', 'Chair'), ('DEP1', '1st Deputy Chair'), ('DEP2', 'Deputy Chair'), ('MEMB', 'Mandatary')], default='MEMB', max_length=5, verbose_name='Officer role'),
        ),
        migrations.AlterField(
            model_name='historicalmandate',
            name='party',
            field=models.CharField(blank=True, help_text='Party/Bloc affiliation (e.g., VSSTÖ, AG, GRAS)', max_length=100, verbose_name='Party affiliation'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='officer_role',
            field=models.CharField(choices=[('CHAIR', 'Chair'), ('DEP1', '1st Deputy Chair'), ('DEP2', 'Deputy Chair'), ('MEMB', 'Mandatary')], default='MEMB', max_length=5, verbose_name='Officer role'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='party',
            field=models.CharField(blank=True, help_text='Party/Bloc affiliation (e.g., VSSTÖ, AG, GRAS)', max_length=100, verbose_name='Party affiliation'),
        ),
    ]
