# Generated by Django 5.2.5 on 2025-12-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0008_alter_historicalmandate_officer_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsession',
            name='session_type',
            field=models.CharField(choices=[('or', 'Regular'), ('ao', 'Extraordinary')], default='or', max_length=2, verbose_name='Session type'),
        ),
        migrations.AlterField(
            model_name='historicalsessionitem',
            name='kind',
            field=models.CharField(choices=[('RES', 'Resolution'), ('PROC', 'Procedural'), ('ELEC', 'Personnel Election by Resolution')], max_length=10, verbose_name='Kind'),
        ),
        migrations.AlterField(
            model_name='historicalsessionitem',
            name='voting_mode',
            field=models.CharField(choices=[('NONE', 'No vote'), ('COUNT', 'Counted vote'), ('NAMED', 'Named vote')], default='NONE', max_length=10, verbose_name='Voting mode'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('or', 'Regular'), ('ao', 'Extraordinary')], default='or', max_length=2, verbose_name='Session type'),
        ),
        migrations.AlterField(
            model_name='sessionitem',
            name='kind',
            field=models.CharField(choices=[('RES', 'Resolution'), ('PROC', 'Procedural'), ('ELEC', 'Personnel Election by Resolution')], max_length=10, verbose_name='Kind'),
        ),
        migrations.AlterField(
            model_name='sessionitem',
            name='voting_mode',
            field=models.CharField(choices=[('NONE', 'No vote'), ('COUNT', 'Counted vote'), ('NAMED', 'Named vote')], default='NONE', max_length=10, verbose_name='Voting mode'),
        ),
    ]
