# Generated by Django 5.2.5 on 2025-12-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0009_alter_historicalsession_session_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.CharField(choices=[('FOR', 'Dafür'), ('AGAINST', 'Dagegen'), ('ABSTAIN', 'Enthaltung')], max_length=10, verbose_name='Vote'),
        ),
    ]
