# Generated by Django 5.2.5 on 2025-12-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0010_alter_vote_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.CharField(choices=[('FOR', 'For'), ('AGAINST', 'Against'), ('ABSTAIN', 'Abstain')], max_length=10, verbose_name='Vote'),
        ),
    ]
